import {randomUUID} from 'node:crypto';
import type {Database} from '../types.js';
import {teamAccess} from './team-authority.js';
import {CollaborationError} from '../../services/collaboration/types.js';
import type {TeamAccess,TeamMember,TeamRow} from '../../services/teams/types.js';

/** Cross-tenant joins are confined to explicit, active team membership authority. */
export class TeamRepository {
 constructor(readonly db:Database,readonly actorId:string){}
 access(teamId:string,manage=false,allowClosed=false){return teamAccess(this.db,this.actorId,teamId,manage,allowClosed);}
 dto(access:TeamAccess){const t=access.team,owner=access.role==='owner',manager=access.role!=='member';return {id:t.id,name:t.name,role:access.role,ownerId:t.owner_id,revision:t.revision,state:t.state,capabilities:{manageMembers:manager,manageAdmins:owner,inviteMembers:manager,inviteAdmins:owner,transferOwner:owner,close:owner,enrollOwnProjects:t.state==='active'}};}
 list(){return (this.db.prepare("SELECT t.id FROM teams t JOIN team_members m ON m.team_id=t.id WHERE m.member_id=? AND m.state='active' AND t.state='active' ORDER BY t.created_at,t.id").all(this.actorId) as {id:string}[]).map(t=>this.dto(this.access(t.id)));}
 create(name:string){return this.db.transaction(()=>{const id=randomUUID(),now=Date.now();this.db.prepare('INSERT INTO teams(id,user_id,owner_id,name,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,this.actorId,this.actorId,name,now,now);this.db.prepare("INSERT INTO team_members(user_id,team_id,member_id,role) VALUES(?,?,?,'admin')").run(this.actorId,id,this.actorId);const a=this.access(id);this.event(a,'team_created',{});return this.dto(a);})();}
 members(a:TeamAccess):TeamMember[]{return (this.db.prepare('SELECT m.member_id,m.role,m.state,m.revision,u.email,u.display_name FROM team_members m JOIN users u ON u.id=m.member_id WHERE m.user_id=? AND m.team_id=? ORDER BY u.email').all(a.team.user_id,a.team.id) as {member_id:string;role:'admin'|'member';state:TeamMember['state'];revision:number;email:string;display_name:string|null}[]).map(m=>({userId:m.member_id,email:m.email,displayName:m.display_name,role:m.member_id===a.team.owner_id?'owner':m.role,state:m.state,revision:m.revision}));}
 member(a:TeamAccess,id:string){const m=this.members(a).find(m=>m.userId===id);if(!m)throw new CollaborationError(404,'TEAM_MEMBER_NOT_FOUND');return m;}
 revision(a:TeamAccess,expected:number){if(a.team.revision!==expected)throw new CollaborationError(409,'STALE_TEAM_REVISION');}
 bump(a:TeamAccess){this.db.prepare('UPDATE teams SET revision=revision+1,updated_at=? WHERE user_id=? AND id=?').run(Date.now(),a.team.user_id,a.team.id);}
 event(a:TeamAccess,kind:string,body:Record<string,unknown>){this.db.prepare('INSERT INTO team_events(id,user_id,team_id,actor_id,kind,body_json,created_at) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),a.team.user_id,a.team.id,this.actorId,kind,JSON.stringify(body),Date.now());}
 owner(a:TeamAccess){if(a.role!=='owner')throw new CollaborationError(403,'TEAM_CAPABILITY_DENIED');}
 rename(teamId:string,name:string,revision:number){return this.db.transaction(()=>{const a=this.access(teamId,true);this.revision(a,revision);this.db.prepare('UPDATE teams SET name=? WHERE user_id=? AND id=?').run(name,a.team.user_id,teamId);this.bump(a);this.event(a,'team_renamed',{});return this.dto(this.access(teamId));})();}
 changeRole(teamId:string,userId:string,role:'admin'|'member',revision:number){return this.db.transaction(()=>{const a=this.access(teamId,true),m=this.member(a,userId);if(m.revision!==revision)throw new CollaborationError(409,'STALE_MEMBER_REVISION');if(userId===a.team.owner_id||userId===this.actorId)throw new CollaborationError(409,'TEAM_OWNER_TRANSFER_REQUIRED');if(a.role!=='owner'&&(role==='admin'||m.role==='admin'))throw new CollaborationError(403,'TEAM_CAPABILITY_DENIED');if(m.state!=='active')throw new CollaborationError(409,'TEAM_MEMBER_NOT_ACTIVE');this.db.prepare('UPDATE team_members SET role=?,revision=revision+1 WHERE user_id=? AND team_id=? AND member_id=?').run(role,a.team.user_id,teamId,userId);this.bump(a);this.event(a,'member_role_changed',{userId,role});return {member:this.member(this.access(teamId),userId),team:this.dto(this.access(teamId))};})();}
 transfer(teamId:string,newOwnerId:string,revision:number){return this.db.transaction(()=>{const a=this.access(teamId,true);this.owner(a);this.revision(a,revision);this.accessTarget(teamId,newOwnerId);this.db.prepare('UPDATE teams SET owner_id=? WHERE user_id=? AND id=?').run(newOwnerId,a.team.user_id,teamId);this.db.prepare("UPDATE team_members SET role='admin',revision=revision+1 WHERE user_id=? AND team_id=? AND member_id IN (?,?)").run(a.team.user_id,teamId,newOwnerId,this.actorId);this.bump(a);this.event(a,'team_owner_transferred',{newOwnerId});return this.dto(this.access(teamId));})();}
 accessTarget(teamId:string,userId:string){return teamAccess(this.db,userId,teamId);}
 close(teamId:string,revision:number){return this.db.transaction(()=>{const a=this.access(teamId,true);this.owner(a);this.revision(a,revision);if(this.db.prepare("SELECT 1 FROM team_projects tp JOIN projects p ON p.id=tp.project_id WHERE tp.user_id=? AND tp.team_id=? AND p.status!='archived'").get(a.team.user_id,teamId))throw new CollaborationError(409,'TEAM_HAS_ACTIVE_PROJECTS');if(this.db.prepare("SELECT 1 FROM delivery_runs r JOIN team_projects p ON p.project_id=r.project_id WHERE p.team_id=? AND r.state IN ('ready','provisioning','revoking')").get(teamId))throw new CollaborationError(409,'TEAM_STOP_PENDING');this.db.prepare("UPDATE teams SET state='closed',revision=revision+1,updated_at=? WHERE user_id=? AND id=?").run(Date.now(),a.team.user_id,teamId);this.event(a,'team_closed',{});return this.dto(this.access(teamId,false,true));})();}
}
