import {createHash,randomBytes,randomUUID} from 'node:crypto';
import type {Database} from '../../db/types.js';
import {TeamRepository} from '../../db/repositories/team-repository.js';
import {UserRepository} from '../../db/repositories/user-repository.js';
import {CollaborationError} from '../collaboration/types.js';
interface Invitation {id:string;user_id:string;team_id:string;token_hash:string;email:string;role:'admin'|'member';issuer_id:string;issuer_revision:number;state:'pending'|'used'|'revoked';expires_at:number;created_at:number}
export const tokenHash=(token:string)=>createHash('sha256').update(token).digest('hex');
export class TeamInvitations {
 constructor(readonly db:Database){}
 dto(i:Invitation){return {id:i.id,email:i.email,role:i.role,state:i.state==='pending'&&i.expires_at<=Date.now()?'expired':i.state,expiresAt:i.expires_at,createdAt:i.created_at};}
 issue(actor:string,teamId:string,email:string,role:'admin'|'member',hours=24){return this.db.transaction(()=>{const r=new TeamRepository(this.db,actor),a=r.access(teamId,true);if(role==='admin')r.owner(a);const token=randomBytes(32).toString('base64url'),id=randomUUID(),now=Date.now();this.db.prepare('INSERT INTO team_invitations(id,user_id,team_id,token_hash,email,role,issuer_id,issuer_revision,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,a.team.user_id,teamId,tokenHash(token),email.trim().toLowerCase(),role,actor,a.membershipRevision,now+hours*3600000,now);r.event(a,'invitation_created',{invitationId:id,role});return {invitation:this.dto(this.getById(a.team.user_id,teamId,id)),token};})();}
 getById(userId:string,teamId:string,id:string){const i=this.db.prepare('SELECT * FROM team_invitations WHERE user_id=? AND team_id=? AND id=?').get(userId,teamId,id) as Invitation|undefined;if(!i)throw new CollaborationError(404,'TEAM_INVITATION_INVALID');return i;}
 list(actor:string,teamId:string){const a=new TeamRepository(this.db,actor).access(teamId,true);return (this.db.prepare('SELECT * FROM team_invitations WHERE user_id=? AND team_id=? ORDER BY created_at DESC').all(a.team.user_id,teamId) as Invitation[]).map(i=>this.dto(i));}
 revoke(actor:string,teamId:string,id:string){const r=new TeamRepository(this.db,actor),a=r.access(teamId,true),i=this.getById(a.team.user_id,teamId,id);if(i.role==='admin')r.owner(a);this.db.prepare("UPDATE team_invitations SET state='revoked' WHERE user_id=? AND team_id=? AND id=? AND state='pending'").run(a.team.user_id,teamId,id);r.event(a,'invitation_revoked',{invitationId:id});return {revoked:true};}
 valid(token:string){const i=this.db.prepare('SELECT * FROM team_invitations WHERE token_hash=?').get(tokenHash(token)) as Invitation|undefined;if(!i||i.state!=='pending'||i.expires_at<=Date.now())throw new CollaborationError(404,'TEAM_INVITATION_INVALID');try{const a=new TeamRepository(this.db,i.issuer_id).access(i.team_id,true);if(a.membershipRevision!==i.issuer_revision||(i.role==='admin'&&a.role!=='owner'))throw new Error('revoked');return {invitation:i,team:a.team};}catch{throw new CollaborationError(404,'TEAM_INVITATION_INVALID');}}
 inspect(token:string,registrationAllowed:boolean){const {invitation:i,team}=this.valid(token),[local,domain]=i.email.split('@');return {invitation:{teamName:team.name,emailHint:`${local?.slice(0,1)}***@${domain}`,role:i.role,expiresAt:i.expires_at,registrationAllowed}};}
 accept(actor:string,token:string){return this.db.transaction(()=>{const {invitation:i}=this.valid(token),user=new UserRepository(this.db).findById(actor);if(!user||user.status!=='active'||user.email.trim().toLowerCase()!==i.email)throw new CollaborationError(403,'TEAM_INVITATION_EMAIL_MISMATCH');const old=this.db.prepare('SELECT state FROM team_members WHERE team_id=? AND member_id=?').get(i.team_id,actor) as {state:string}|undefined;if(old?.state==='leaving')throw new CollaborationError(409,'TEAM_STOP_PENDING');if(old?.state==='active')throw new CollaborationError(409,'TEAM_ALREADY_MEMBER');this.db.prepare("INSERT INTO team_members(user_id,team_id,member_id,role) VALUES(?,?,?,?) ON CONFLICT(team_id,member_id) DO UPDATE SET role=excluded.role,state='active',revision=team_members.revision+1").run(i.user_id,i.team_id,actor,i.role);this.db.prepare("UPDATE team_invitations SET state='used',used_at=?,used_by=? WHERE id=? AND state='pending'").run(Date.now(),actor,i.id);const r=new TeamRepository(this.db,actor),a=r.access(i.team_id);r.bump(a);r.event(a,'invitation_accepted',{invitationId:i.id});return {team:r.dto(r.access(i.team_id)),membership:r.member(a,actor)};})();}
 register(token:string,email:string,passwordHash:string){return this.db.transaction(()=>{const {invitation}=this.valid(token);if(email.trim().toLowerCase()!==invitation.email)throw new CollaborationError(403,'TEAM_INVITATION_EMAIL_MISMATCH');const users=new UserRepository(this.db);if(users.count()===0)throw new CollaborationError(403,'TEAM_INVITATION_INVALID');if(users.findByEmail(email))throw new CollaborationError(409,'EMAIL_ALREADY_REGISTERED');const user=users.create(email,passwordHash,{role:'user'});return {user,...this.accept(user.id,token)};})();}
}
