import { useLanguage } from "@/hooks/use-language";

const zh = {
  title: "定时自动化",
  description: "创建按计划自动运行的 Copilot 任务，结果投递到会话与通知。",
  list: "自动化",
  create: "新建",
  prompt: "任务提示词",
  scheduleKind: "调度类型",
  expression: "表达式",
  save: "创建",
  createFailed: "创建失败，请检查输入。",
  empty: "暂无自动化，点击「新建」创建。",
  deleteConfirm: "删除该自动化？不可撤销。",
  runNow: "立即运行",
  pause: "暂停",
  enable: "启用",
  suggestions: "推荐自动化",
  accept: "接受",
  dismiss: "忽略",
  statusEnabled: "已启用",
  statusPaused: "已暂停",
  statusDraft: "草稿",
  invalidCron: "表达式格式不正确：cron 需为 5 段（分 时 日 月 周）。",
};
const en: typeof zh = {
  title: "Scheduled automations",
  description: "Create Copilot tasks that run on a schedule and deliver results to your conversation and notifications.",
  list: "Automations",
  create: "New",
  prompt: "Task prompt",
  scheduleKind: "Schedule type",
  expression: "Expression",
  save: "Create",
  createFailed: "Creation failed; check your input.",
  empty: "No automations yet. Click \"New\" to create one.",
  deleteConfirm: "Delete this automation? This cannot be undone.",
  runNow: "Run now",
  pause: "Pause",
  enable: "Enable",
  suggestions: "Suggested automations",
  accept: "Accept",
  dismiss: "Dismiss",
  statusEnabled: "Enabled",
  statusPaused: "Paused",
  statusDraft: "Draft",
  invalidCron: "Invalid expression: cron needs 5 fields (minute hour day month weekday).",
};
const zhTW: typeof zh = {
  title: "定時自動化",
  description: "建立按計畫自動執行的 Copilot 任務，結果投遞到工作階段與通知。",
  list: "自動化",
  create: "新建",
  prompt: "任務提示詞",
  scheduleKind: "排程類型",
  expression: "運算式",
  save: "建立",
  createFailed: "建立失敗，請檢查輸入。",
  empty: "尚無自動化，點擊「新建」建立。",
  deleteConfirm: "刪除此自動化？無法復原。",
  runNow: "立即執行",
  pause: "暫停",
  enable: "啟用",
  suggestions: "推薦自動化",
  accept: "接受",
  dismiss: "忽略",
  statusEnabled: "已啟用",
  statusPaused: "已暫停",
  statusDraft: "草稿",
  invalidCron: "運算式格式不正確：cron 需為 5 段（分 時 日 月 週）。",
};
export function useAutomationsCopy() {
  const { language } = useLanguage();
  return language === "en" ? en : language === "zh-TW" ? zhTW : zh;
}
