import { useLanguage } from "@/hooks/use-language";
import type { FeishuNotificationType } from "@/lib/feishu-notifications-api";

const zh = {
  navAriaLabel: "Copilot 设置导航",
  navGeneral: "常规",
  navExtensions: "扩展",
  navChannels: "远程渠道",
  navAutomations: "自动化",
  backToChat: "返回对话",
  channelsCardTitle: "远程渠道",
  channelsCardDescription: "配置飞书与 Telegram 远程操作：应用接入、身份确认与项目绑定。",
  channelPlatformLabel: "渠道平台",
  channelStateNotConnected: "未接入",
  channelStatePairing: "待配对",
  channelStateAuthorization: "待授权",
  channelStateRunning: "运行中",
  channelStateStopped: "已停止",
  channelStateUnknown: "待核查",
  diagnosticsFailedNotice: (count: number) => `诊断存在 ${count} 项未通过。`,
  diagnosticsExpand: "展开诊断",
  diagnosticsCollapse: "收起诊断",
  diagnosticsStatusUntested: "未验证",
  diagnosticsStatusPending: "进行中",
  diagnosticsStatusFailed: "未通过",
  copyCommand: "复制命令",
  commandCopied: "已复制",
  modifyConfig: "修改配置",
  editAllowlist: "编辑白名单",
  setAllowlist: "设置白名单",
  allowlistEmpty: "尚未设置聊天白名单。",
  identitiesEmpty: "暂无已确认身份。",
  bindingsEmpty: "尚无渠道绑定。",
  emergencyStopTitle: (name: string) => `确认紧急停止${name}？`,
  emergencyStopDescription: "紧急停止会阻止后续入站消息与操作；已经发生的操作无法撤回。",
  emergencyStopConfirm: "确认停止",
  dialogCancel: "取消",
  memoryScopeGlobal: "全局",
  memoryScopeProject: "项目",
  memoryScopeSession: "会话",
  memoryKindFact: "事实",
  memoryKindPreference: "偏好",
  memoryKindDecision: "决策",
  memoryKindProjectNote: "项目备注",
  manageModels: "管理模型",
  autonomyTitle: "派发自主权",
  autonomyDescription: "允许 Copilot 程序化控制哪些 CLI 适配器。未启用的适配器在派发时会被安全策略拒绝（ADAPTER_AUTONOMY_UNVERIFIED）。",
  autonomyEmptyNote: "未启用任何适配器：所有程序化派发都会被拒绝，需要手动向 CLI 提交指令。",
  autonomyInstalled: "本机已检测到",
  autonomyMissing: "未检测到 CLI",
  autonomyAutoDispatch: "项目任务自动推进",
  autonomyAutoDispatchDescription: "CLI 报告任务完成/失败后，自动把对应工作项推进到待评审/受阻。",
  autonomyAutoDispatchBlocked: "需先启用至少一个适配器",
  autonomySaving: "正在保存…",
  autonomySaved: "派发自主权已保存。",
  autonomySaveError: "保存失败，请重试。",
  autonomyLoadError: "加载失败",
  autonomyRetry: "重试",
  autonomyReadonly: "运行时设置已被 FORGEBADGER_RUNTIME_SETTINGS_READONLY 锁定为只读，请修改 .env 并重启 Gateway。",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "设置页",
  notifyTitle: "飞书通知",
  notifyDescription: "选择已确认的私聊或已核验的群聊接收通知卡片。保存仅授权通知推送，不改变远程命令白名单或项目操作权限。",
  notifySwitchAria: "接收 ForgeBadger 通知",
  notifyLoading: "正在加载通知设置…",
  notifyLoadError: "通知设置加载失败。",
  notifyReload: "重新加载通知设置",
  notifyTargetLabel: "通知接收位置",
  notifyTargetPlaceholder: "选择私聊或群聊",
  notifyTargetStale: "已失效的接收位置，请重新选择",
  notifyKindGroup: "群聊",
  notifyKindPrivate: "私聊",
  notifyUnavailableSuffix: "不可用",
  notifyRefreshTargets: "刷新接收位置",
  notifyPrivateHint: "私聊来自已确认身份；刷新会核验已配置或已使用的群聊。机器人需在群内，并具备读取群列表与群成员状态的权限。",
  notifyGroupNotice: (name: string) => `所选通知将发送到群“${name}”，群成员均可查看。`,
  notifyTypesLegend: "通知类型",
  notifyWebLabel: "ForgeBadger Web 地址（可选）",
  notifyWebAria: "ForgeBadger Web 地址",
  notifyWebHint: "填写飞书所在设备能访问的地址，卡片才显示查看按钮；localhost 只指向当前设备。留空仍可接收卡片摘要。卡片不提供直接审批操作。",
  notifyBlockerFallback: "请检查通知配置。",
  notifySave: "保存通知设置",
  notifyTest: "发送测试卡片",
  notifyActionFailed: (action: string, detail: string) => `${action}失败。${detail}`,
  notifyActionRefresh: "刷新接收位置",
  notifyActionSave: "保存",
  notifyActionTest: "测试通知入队",
  notifyAuthExpired: "登录已失效，请重新登录。",
  notifyGenericError: "暂时无法完成请求，请检查 Gateway 连接后重试。",
  notifyRefreshOk: "接收位置已刷新。",
  notifyRefreshNoGroup: "未发现可用的已配置群聊，请确认机器人已加入该群。已确认私聊仍可直接选择。",
  notifySavedOn: "飞书通知已开启，只推送之后产生的通知。",
  notifySavedOff: "飞书通知已关闭，尚未发送的通知已取消。",
  notifyTestQueued: "测试卡片已入队，请查看下方投递状态和所选会话。",
  notifyDeliveriesTitle: "最近通知投递",
  notifyDeliveriesHint: "飞书已接收不代表已读；结果不确定时请先核对接收会话，系统不会自动重发。",
  notifyDeliveriesLoading: "正在加载投递记录…",
  notifyDeliveriesLoadError: "投递记录加载失败。",
  notifyDeliveriesEmpty: "暂无通知投递记录。",
  notifyTestCard: "测试卡片",
  notifyDeliveryFallback: "通知",
  notifyTypes: {
    attention: "需要处理 / 等待审批",
    failure: "任务失败 / 权限被拒绝",
    completion: "任务完成",
    lifecycle: "任务中断 / 会话结束",
    app_action: "应用操作结果",
    automation: "自动化任务结果",
  } satisfies Record<FeishuNotificationType, string>,
  notifyStatuses: {
    pending: "待发送",
    sending: "发送中",
    delivered: "飞书已接收",
    failed: "发送失败",
    unknown: "结果不确定",
    cancelled: "已取消",
  } as Record<string, string>,
  notifyBlockers: {
    IDENTITY_INVALID: "请先完成私聊身份确认。",
    ACCOUNT_CHANGED: "账号配置已变化，请重新配对身份。",
    CHANNEL_DISABLED: "请先启用飞书应用，或解除紧急停止。",
    USER_DISABLED: "当前账号已停用。",
    TARGET_INVALID: "请选择一个已确认的私聊或已核验的群聊。",
    TARGET_UNAVAILABLE: "接收位置已不可用，请刷新列表并重新选择。",
    TARGET_CHANGED: "接收位置已变化，请重新选择并保存。",
    TARGET_CONFLICT: "接收位置与旧版私聊设置冲突，请刷新页面后重新选择。",
  } as Record<string, string>,
  notifyErrors: {
    CONFIG_CONFLICT: "配置已在其他页面更新，请重新加载通知设置后再修改。",
    WEB_URL_INVALID: "Web 地址格式不正确，请使用完整的 http:// 或 https:// 地址，不包含账号密码、查询参数或 # 片段；也可以留空。",
    TYPES_REQUIRED: "请至少选择一种通知类型。",
    INPUT_INVALID: "提交的通知设置格式不正确，请检查输入。",
    SUBSCRIPTION_DISABLED: "请先开启并保存通知设置。",
    QUEUE_FULL: "待发送通知已达上限，请等待队列处理后再测试。",
    INTERNAL_ERROR: "服务端暂时无法处理通知请求，请稍后重试。",
    DIRECTORY_PERMISSION_REQUIRED: "飞书应用缺少读取群聊列表或群成员状态的权限，请在飞书开放平台补齐权限后刷新。",
    DIRECTORY_UNAVAILABLE: "暂时无法核验飞书群聊，请检查应用权限及网络后刷新；已保存的设置不会被清空。",
    DIRECTORY_INCOMPLETE: "群聊列表未能完整读取，请稍后刷新。",
  },
};
const en: typeof zh = {
  navAriaLabel: "Copilot settings navigation",
  navGeneral: "General",
  navExtensions: "Extensions",
  navChannels: "Channels",
  navAutomations: "Automations",
  backToChat: "Back to chat",
  channelsCardTitle: "Channels",
  channelsCardDescription: "Set up Feishu and Telegram remote operation: app connection, identity confirmation, and project binding.",
  channelPlatformLabel: "Channel platform",
  channelStateNotConnected: "Not connected",
  channelStatePairing: "Pairing",
  channelStateAuthorization: "Authorization",
  channelStateRunning: "Running",
  channelStateStopped: "Stopped",
  channelStateUnknown: "Check pending",
  diagnosticsFailedNotice: (count: number) => `${count} diagnostic check${count === 1 ? "" : "s"} failing.`,
  diagnosticsExpand: "Show diagnostics",
  diagnosticsCollapse: "Hide diagnostics",
  diagnosticsStatusUntested: "Untested",
  diagnosticsStatusPending: "In progress",
  diagnosticsStatusFailed: "Failing",
  copyCommand: "Copy command",
  commandCopied: "Copied",
  modifyConfig: "Modify configuration",
  editAllowlist: "Edit allowlist",
  setAllowlist: "Set allowlist",
  allowlistEmpty: "No chat allowlist configured yet.",
  identitiesEmpty: "No confirmed identities yet.",
  bindingsEmpty: "No channel bindings yet.",
  emergencyStopTitle: (name: string) => `Emergency stop ${name}?`,
  emergencyStopDescription: "Emergency stop blocks further inbound messages and operations; operations already performed cannot be undone.",
  emergencyStopConfirm: "Stop now",
  dialogCancel: "Cancel",
  memoryScopeGlobal: "Global",
  memoryScopeProject: "Project",
  memoryScopeSession: "Session",
  memoryKindFact: "Fact",
  memoryKindPreference: "Preference",
  memoryKindDecision: "Decision",
  memoryKindProjectNote: "Project note",
  manageModels: "Manage models",
  autonomyTitle: "Dispatch autonomy",
  autonomyDescription: "Choose which CLI adapters Copilot may control programmatically. Dispatching to an adapter without autonomy is denied by the security policy (ADAPTER_AUTONOMY_UNVERIFIED).",
  autonomyEmptyNote: "No adapter enabled: every programmatic dispatch is denied; submit instructions to the CLI manually.",
  autonomyInstalled: "detected on this machine",
  autonomyMissing: "CLI not detected",
  autonomyAutoDispatch: "Auto-advance project tasks",
  autonomyAutoDispatchDescription: "When the CLI reports task completion/failure, advance the linked work item to ready-for-review/blocked automatically.",
  autonomyAutoDispatchBlocked: "Enable at least one adapter first",
  autonomySaving: "Saving…",
  autonomySaved: "Dispatch autonomy saved.",
  autonomySaveError: "Save failed. Please retry.",
  autonomyLoadError: "Failed to load",
  autonomyRetry: "Retry",
  autonomyReadonly: "Runtime settings are locked read-only by FORGEBADGER_RUNTIME_SETTINGS_READONLY; edit .env and restart the Gateway.",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "Settings page",
  notifyTitle: "Feishu notifications",
  notifyDescription: "Choose a confirmed private chat or a verified group chat to receive notification cards. Saving only authorizes notification delivery; it does not change the remote command allowlist or project operation permissions.",
  notifySwitchAria: "Receive ForgeBadger notifications",
  notifyLoading: "Loading notification settings…",
  notifyLoadError: "Failed to load notification settings.",
  notifyReload: "Reload notification settings",
  notifyTargetLabel: "Notification destination",
  notifyTargetPlaceholder: "Choose a private or group chat",
  notifyTargetStale: "This destination is no longer valid; choose again",
  notifyKindGroup: "Group",
  notifyKindPrivate: "Private",
  notifyUnavailableSuffix: "unavailable",
  notifyRefreshTargets: "Refresh destinations",
  notifyPrivateHint: "Private chats come from confirmed identities; refresh verifies configured or previously used group chats. The bot must be in the group with permission to read the group list and member status.",
  notifyGroupNotice: (name: string) => `Notifications will be sent to the group “${name}”; all group members can see them.`,
  notifyTypesLegend: "Notification types",
  notifyWebLabel: "ForgeBadger web address (optional)",
  notifyWebAria: "ForgeBadger web address",
  notifyWebHint: "Enter an address reachable from the device running Feishu so the card shows a view button; localhost only points at the current device. Cards still deliver summaries when empty. Cards do not offer direct approval actions.",
  notifyBlockerFallback: "Check the notification configuration.",
  notifySave: "Save notification settings",
  notifyTest: "Send test card",
  notifyActionFailed: (action: string, detail: string) => `${action} failed. ${detail}`,
  notifyActionRefresh: "Refresh destinations",
  notifyActionSave: "Save",
  notifyActionTest: "Test notification enqueue",
  notifyAuthExpired: "Your session has expired; sign in again.",
  notifyGenericError: "The request could not be completed; check the Gateway connection and retry.",
  notifyRefreshOk: "Destinations refreshed.",
  notifyRefreshNoGroup: "No configured group chat is available. Make sure the bot has joined the group; confirmed private chats can still be selected.",
  notifySavedOn: "Feishu notifications are on; only notifications created from now on are delivered.",
  notifySavedOff: "Feishu notifications are off; unsent notifications have been cancelled.",
  notifyTestQueued: "Test card queued; check the delivery status below and the selected chat.",
  notifyDeliveriesTitle: "Recent notification deliveries",
  notifyDeliveriesHint: "Received by Feishu does not mean read; when the result is uncertain, verify the destination chat first. The system does not resend automatically.",
  notifyDeliveriesLoading: "Loading delivery records…",
  notifyDeliveriesLoadError: "Failed to load delivery records.",
  notifyDeliveriesEmpty: "No notification deliveries yet.",
  notifyTestCard: "Test card",
  notifyDeliveryFallback: "Notification",
  notifyTypes: {
    attention: "Needs action / awaiting approval",
    failure: "Task failed / permission denied",
    completion: "Task completed",
    lifecycle: "Task interrupted / session ended",
    app_action: "App action result",
    automation: "Automation task result",
  },
  notifyStatuses: {
    pending: "Pending",
    sending: "Sending",
    delivered: "Received by Feishu",
    failed: "Delivery failed",
    unknown: "Result uncertain",
    cancelled: "Cancelled",
  },
  notifyBlockers: {
    IDENTITY_INVALID: "Confirm your private-chat identity first.",
    ACCOUNT_CHANGED: "The account configuration changed; re-pair your identity.",
    CHANNEL_DISABLED: "Enable the Feishu app first, or lift the emergency stop.",
    USER_DISABLED: "This account is disabled.",
    TARGET_INVALID: "Choose a confirmed private chat or a verified group chat.",
    TARGET_UNAVAILABLE: "The destination is no longer available; refresh the list and choose again.",
    TARGET_CHANGED: "The destination has changed; choose it again and save.",
    TARGET_CONFLICT: "The destination conflicts with the legacy private-chat settings; refresh the page and choose again.",
  },
  notifyErrors: {
    CONFIG_CONFLICT: "The settings were updated on another page; reload the notification settings before editing.",
    WEB_URL_INVALID: "The web address format is invalid; use a full http:// or https:// URL without credentials, query parameters, or # fragments, or leave it empty.",
    TYPES_REQUIRED: "Select at least one notification type.",
    INPUT_INVALID: "The submitted notification settings are malformed; check your input.",
    SUBSCRIPTION_DISABLED: "Enable and save the notification settings first.",
    QUEUE_FULL: "Too many notifications are pending; wait for the queue to clear and try again.",
    INTERNAL_ERROR: "The server could not process the notification request; try again later.",
    DIRECTORY_PERMISSION_REQUIRED: "The Feishu app lacks permission to read the group chat list or member status; grant the missing permissions on the Feishu developer console and refresh.",
    DIRECTORY_UNAVAILABLE: "Group chats cannot be verified right now; check the app permissions and network, then refresh. Saved settings are not cleared.",
    DIRECTORY_INCOMPLETE: "The group list was not fully read; refresh later.",
  },
};
const zhTW: typeof zh = {
  ...zh,
  navAriaLabel: "Copilot 設定導覽",
  navGeneral: "一般",
  navExtensions: "擴充",
  navChannels: "遠端渠道",
  navAutomations: "自動化",
  backToChat: "返回對話",
  channelsCardTitle: "遠端渠道",
  channelsCardDescription: "設定飛書與 Telegram 遠端操作：應用接入、身份確認與專案綁定。",
  channelPlatformLabel: "渠道平台",
  channelStateNotConnected: "未接入",
  channelStatePairing: "待配對",
  channelStateAuthorization: "待授權",
  channelStateRunning: "執行中",
  channelStateStopped: "已停止",
  channelStateUnknown: "待核查",
  diagnosticsFailedNotice: (count: number) => `診斷存在 ${count} 項未通過。`,
  diagnosticsExpand: "展開診斷",
  diagnosticsCollapse: "收起診斷",
  diagnosticsStatusUntested: "未驗證",
  diagnosticsStatusPending: "進行中",
  diagnosticsStatusFailed: "未通過",
  copyCommand: "複製指令",
  commandCopied: "已複製",
  modifyConfig: "修改配置",
  editAllowlist: "編輯白名單",
  setAllowlist: "設定白名單",
  allowlistEmpty: "尚未設定聊天白名單。",
  identitiesEmpty: "暫無已確認身份。",
  bindingsEmpty: "尚無渠道綁定。",
  emergencyStopTitle: (name: string) => `確認緊急停止${name}？`,
  emergencyStopDescription: "緊急停止會阻止後續入站訊息與操作；已經發生的操作無法撤回。",
  emergencyStopConfirm: "確認停止",
  dialogCancel: "取消",
  memoryScopeGlobal: "全域",
  memoryScopeProject: "專案",
  memoryScopeSession: "工作階段",
  memoryKindFact: "事實",
  memoryKindPreference: "偏好",
  memoryKindDecision: "決策",
  memoryKindProjectNote: "專案備註",
  manageModels: "管理模型",
  autonomyTitle: "下發自主權",
  autonomyDescription: "允許 Copilot 程序化控制哪些 CLI 介面器。未啟用的介面器在下發時會被安全策略拒絕（ADAPTER_AUTONOMY_UNVERIFIED）。",
  autonomyEmptyNote: "未啟用任何介面器：所有程序化下發都會被拒絕，需要手動向 CLI 提交指令。",
  autonomyInstalled: "本機已偵測到",
  autonomyMissing: "未偵測到 CLI",
  autonomyAutoDispatch: "專案任務自動推進",
  autonomyAutoDispatchDescription: "CLI 回報任務完成/失敗後，自動把對應工作項推進到待評審/受阻。",
  autonomyAutoDispatchBlocked: "需先啟用至少一個介面器",
  autonomySaving: "正在儲存…",
  autonomySaved: "下發自主權已儲存。",
  autonomySaveError: "儲存失敗，請重試。",
  autonomyLoadError: "載入失敗",
  autonomyRetry: "重試",
  autonomyReadonly: "執行時間設定已被 FORGEBADGER_RUNTIME_SETTINGS_READONLY 鎖定為唯讀，請修改 .env 並重啟 Gateway。",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "設定頁",
  notifyTitle: "飛書通知",
  notifyDescription: "選擇已確認的私聊或已核驗的群聊接收通知卡片。儲存僅授權通知推送，不改變遠端指令白名單或專案操作權限。",
  notifySwitchAria: "接收 ForgeBadger 通知",
  notifyLoading: "正在載入通知設定…",
  notifyLoadError: "通知設定載入失敗。",
  notifyReload: "重新載入通知設定",
  notifyTargetLabel: "通知接收位置",
  notifyTargetPlaceholder: "選擇私聊或群聊",
  notifyTargetStale: "已失效的接收位置，請重新選擇",
  notifyKindGroup: "群聊",
  notifyKindPrivate: "私聊",
  notifyUnavailableSuffix: "不可用",
  notifyRefreshTargets: "重新整理接收位置",
  notifyPrivateHint: "私聊來自已確認身份；重新整理會核驗已配置或已使用的群聊。機器人需在群內，並具備讀取群列表與群成員狀態的權限。",
  notifyGroupNotice: (name: string) => `所選通知將傳送到群「${name}」，群成員均可查看。`,
  notifyTypesLegend: "通知類型",
  notifyWebLabel: "ForgeBadger Web 地址（可選）",
  notifyWebAria: "ForgeBadger Web 地址",
  notifyWebHint: "填寫飛書所在裝置能存取的地址，卡片才顯示查看按鈕；localhost 只指向目前裝置。留空仍可接收卡片摘要。卡片不提供直接審批操作。",
  notifyBlockerFallback: "請檢查通知配置。",
  notifySave: "儲存通知設定",
  notifyTest: "傳送測試卡片",
  notifyActionFailed: (action: string, detail: string) => `${action}失敗。${detail}`,
  notifyActionRefresh: "重新整理接收位置",
  notifyActionSave: "儲存",
  notifyActionTest: "測試通知入隊",
  notifyAuthExpired: "登入已失效，請重新登入。",
  notifyGenericError: "暫時無法完成請求，請檢查 Gateway 連線後重試。",
  notifyRefreshOk: "接收位置已重新整理。",
  notifyRefreshNoGroup: "未發現可用的已配置群聊，請確認機器人已加入該群。已確認私聊仍可直接選擇。",
  notifySavedOn: "飛書通知已開啟，只推送之後產生的通知。",
  notifySavedOff: "飛書通知已關閉，尚未傳送的通知已取消。",
  notifyTestQueued: "測試卡片已入隊，請查看下方投遞狀態與所選會話。",
  notifyDeliveriesTitle: "最近通知投遞",
  notifyDeliveriesHint: "飛書已接收不代表已讀；結果不確定時請先核對接收會話，系統不會自動重發。",
  notifyDeliveriesLoading: "正在載入投遞記錄…",
  notifyDeliveriesLoadError: "投遞記錄載入失敗。",
  notifyDeliveriesEmpty: "暫無通知投遞記錄。",
  notifyTestCard: "測試卡片",
  notifyDeliveryFallback: "通知",
  notifyTypes: {
    attention: "需要處理 / 等待審批",
    failure: "任務失敗 / 權限被拒絕",
    completion: "任務完成",
    lifecycle: "任務中斷 / 會話結束",
    app_action: "應用操作結果",
    automation: "自動化任務結果",
  },
  notifyStatuses: {
    pending: "待發送",
    sending: "發送中",
    delivered: "飛書已接收",
    failed: "發送失敗",
    unknown: "結果不確定",
    cancelled: "已取消",
  },
  notifyBlockers: {
    IDENTITY_INVALID: "請先完成私聊身份確認。",
    ACCOUNT_CHANGED: "帳號配置已變化，請重新配對身份。",
    CHANNEL_DISABLED: "請先啟用飛書應用，或解除緊急停止。",
    USER_DISABLED: "目前帳號已停用。",
    TARGET_INVALID: "請選擇一個已確認的私聊或已核驗的群聊。",
    TARGET_UNAVAILABLE: "接收位置已不可用，請重新整理列表並重新選擇。",
    TARGET_CHANGED: "接收位置已變化，請重新選擇並儲存。",
    TARGET_CONFLICT: "接收位置與舊版私聊設定衝突，請重新整理頁面後重新選擇。",
  },
  notifyErrors: {
    CONFIG_CONFLICT: "配置已在其他頁面更新，請重新載入通知設定後再修改。",
    WEB_URL_INVALID: "Web 地址格式不正確，請使用完整的 http:// 或 https:// 地址，不包含帳號密碼、查詢參數或 # 片段；也可以留空。",
    TYPES_REQUIRED: "請至少選擇一種通知類型。",
    INPUT_INVALID: "提交的通知設定格式不正確，請檢查輸入。",
    SUBSCRIPTION_DISABLED: "請先開啟並儲存通知設定。",
    QUEUE_FULL: "待發送通知已達上限，請等待佇列處理後再測試。",
    INTERNAL_ERROR: "服務端暫時無法處理通知請求，請稍後重試。",
    DIRECTORY_PERMISSION_REQUIRED: "飛書應用缺少讀取群聊列表或群成員狀態的權限，請在飛書開放平台補齊權限後重新整理。",
    DIRECTORY_UNAVAILABLE: "暫時無法核驗飛書群聊，請檢查應用權限及網路後重新整理；已儲存的設定不會被清空。",
    DIRECTORY_INCOMPLETE: "群聊列表未能完整讀取，請稍後重新整理。",
  },
};
export function useSettingsCopy() { const { language } = useLanguage(); return language === "en" ? en : language === "zh-TW" ? zhTW : zh; }
