import { useLanguage } from "@/hooks/use-language";

const zh = {
  navAriaLabel: "Copilot 设置导航",
  navGeneral: "常规",
  navExtensions: "扩展",
  navChannels: "远程渠道",
  navAutomations: "自动化",
  backToChat: "返回对话",
  channelsCardTitle: "远程渠道",
  channelsCardDescription: "配置飞书与 Telegram 远程操作：应用接入、身份确认与项目绑定。",
  channelPlatformLabel: "渠道平台",
  channelStateNotConnected: "未接入",
  channelStatePairing: "待配对",
  channelStateAuthorization: "待授权",
  channelStateRunning: "运行中",
  channelStateStopped: "已停止",
  channelStateUnknown: "待核查",
  diagnosticsFailedNotice: (count: number) => `诊断存在 ${count} 项未通过。`,
  diagnosticsExpand: "展开诊断",
  diagnosticsCollapse: "收起诊断",
  diagnosticsStatusUntested: "未验证",
  diagnosticsStatusPending: "进行中",
  diagnosticsStatusFailed: "未通过",
  copyCommand: "复制命令",
  commandCopied: "已复制",
  modifyConfig: "修改配置",
  editAllowlist: "编辑白名单",
  setAllowlist: "设置白名单",
  allowlistEmpty: "尚未设置聊天白名单。",
  identitiesEmpty: "暂无已确认身份。",
  bindingsEmpty: "尚无渠道绑定。",
  emergencyStopTitle: (name: string) => `确认紧急停止${name}？`,
  emergencyStopDescription: "紧急停止会阻止后续入站消息与操作；已经发生的操作无法撤回。",
  emergencyStopConfirm: "确认停止",
  dialogCancel: "取消",
  memoryScopeGlobal: "全局",
  memoryScopeProject: "项目",
  memoryScopeSession: "会话",
  memoryKindFact: "事实",
  memoryKindPreference: "偏好",
  memoryKindDecision: "决策",
  memoryKindProjectNote: "项目备注",
  manageModels: "管理模型",
  autonomyTitle: "派发自主权",
  autonomyDescription: "允许 Copilot 程序化控制哪些 CLI 适配器。未启用的适配器在派发时会被安全策略拒绝（ADAPTER_AUTONOMY_UNVERIFIED）。",
  autonomyEmptyNote: "未启用任何适配器：所有程序化派发都会被拒绝，需要手动向 CLI 提交指令。",
  autonomyInstalled: "本机已检测到",
  autonomyMissing: "未检测到 CLI",
  autonomyAutoDispatch: "项目任务自动推进",
  autonomyAutoDispatchDescription: "CLI 报告任务完成/失败后，自动把对应工作项推进到待评审/受阻。",
  autonomyAutoDispatchBlocked: "需先启用至少一个适配器",
  autonomySaving: "正在保存…",
  autonomySaved: "派发自主权已保存。",
  autonomySaveError: "保存失败，请重试。",
  autonomyLoadError: "加载失败",
  autonomyRetry: "重试",
  autonomyReadonly: "运行时设置已被 FORGEBADGER_RUNTIME_SETTINGS_READONLY 锁定为只读，请修改 .env 并重启 Gateway。",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "设置页",
};
const en: typeof zh = {
  navAriaLabel: "Copilot settings navigation",
  navGeneral: "General",
  navExtensions: "Extensions",
  navChannels: "Channels",
  navAutomations: "Automations",
  backToChat: "Back to chat",
  channelsCardTitle: "Channels",
  channelsCardDescription: "Set up Feishu and Telegram remote operation: app connection, identity confirmation, and project binding.",
  channelPlatformLabel: "Channel platform",
  channelStateNotConnected: "Not connected",
  channelStatePairing: "Pairing",
  channelStateAuthorization: "Authorization",
  channelStateRunning: "Running",
  channelStateStopped: "Stopped",
  channelStateUnknown: "Check pending",
  diagnosticsFailedNotice: (count: number) => `${count} diagnostic check${count === 1 ? "" : "s"} failing.`,
  diagnosticsExpand: "Show diagnostics",
  diagnosticsCollapse: "Hide diagnostics",
  diagnosticsStatusUntested: "Untested",
  diagnosticsStatusPending: "In progress",
  diagnosticsStatusFailed: "Failing",
  copyCommand: "Copy command",
  commandCopied: "Copied",
  modifyConfig: "Modify configuration",
  editAllowlist: "Edit allowlist",
  setAllowlist: "Set allowlist",
  allowlistEmpty: "No chat allowlist configured yet.",
  identitiesEmpty: "No confirmed identities yet.",
  bindingsEmpty: "No channel bindings yet.",
  emergencyStopTitle: (name: string) => `Emergency stop ${name}?`,
  emergencyStopDescription: "Emergency stop blocks further inbound messages and operations; operations already performed cannot be undone.",
  emergencyStopConfirm: "Stop now",
  dialogCancel: "Cancel",
  memoryScopeGlobal: "Global",
  memoryScopeProject: "Project",
  memoryScopeSession: "Session",
  memoryKindFact: "Fact",
  memoryKindPreference: "Preference",
  memoryKindDecision: "Decision",
  memoryKindProjectNote: "Project note",
  manageModels: "Manage models",
  autonomyTitle: "Dispatch autonomy",
  autonomyDescription: "Choose which CLI adapters Copilot may control programmatically. Dispatching to an adapter without autonomy is denied by the security policy (ADAPTER_AUTONOMY_UNVERIFIED).",
  autonomyEmptyNote: "No adapter enabled: every programmatic dispatch is denied; submit instructions to the CLI manually.",
  autonomyInstalled: "detected on this machine",
  autonomyMissing: "CLI not detected",
  autonomyAutoDispatch: "Auto-advance project tasks",
  autonomyAutoDispatchDescription: "When the CLI reports task completion/failure, advance the linked work item to ready-for-review/blocked automatically.",
  autonomyAutoDispatchBlocked: "Enable at least one adapter first",
  autonomySaving: "Saving…",
  autonomySaved: "Dispatch autonomy saved.",
  autonomySaveError: "Save failed. Please retry.",
  autonomyLoadError: "Failed to load",
  autonomyRetry: "Retry",
  autonomyReadonly: "Runtime settings are locked read-only by FORGEBADGER_RUNTIME_SETTINGS_READONLY; edit .env and restart the Gateway.",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "Settings page",
};
const zhTW: typeof zh = {
  ...zh,
  navAriaLabel: "Copilot 設定導覽",
  navGeneral: "一般",
  navExtensions: "擴充",
  navChannels: "遠端渠道",
  navAutomations: "自動化",
  backToChat: "返回對話",
  channelsCardTitle: "遠端渠道",
  channelsCardDescription: "設定飛書與 Telegram 遠端操作：應用接入、身份確認與專案綁定。",
  channelPlatformLabel: "渠道平台",
  channelStateNotConnected: "未接入",
  channelStatePairing: "待配對",
  channelStateAuthorization: "待授權",
  channelStateRunning: "執行中",
  channelStateStopped: "已停止",
  channelStateUnknown: "待核查",
  diagnosticsFailedNotice: (count: number) => `診斷存在 ${count} 項未通過。`,
  diagnosticsExpand: "展開診斷",
  diagnosticsCollapse: "收起診斷",
  diagnosticsStatusUntested: "未驗證",
  diagnosticsStatusPending: "進行中",
  diagnosticsStatusFailed: "未通過",
  copyCommand: "複製指令",
  commandCopied: "已複製",
  modifyConfig: "修改配置",
  editAllowlist: "編輯白名單",
  setAllowlist: "設定白名單",
  allowlistEmpty: "尚未設定聊天白名單。",
  identitiesEmpty: "暫無已確認身份。",
  bindingsEmpty: "尚無渠道綁定。",
  emergencyStopTitle: (name: string) => `確認緊急停止${name}？`,
  emergencyStopDescription: "緊急停止會阻止後續入站訊息與操作；已經發生的操作無法撤回。",
  emergencyStopConfirm: "確認停止",
  dialogCancel: "取消",
  memoryScopeGlobal: "全域",
  memoryScopeProject: "專案",
  memoryScopeSession: "工作階段",
  memoryKindFact: "事實",
  memoryKindPreference: "偏好",
  memoryKindDecision: "決策",
  memoryKindProjectNote: "專案備註",
  manageModels: "管理模型",
  autonomyTitle: "下發自主權",
  autonomyDescription: "允許 Copilot 程序化控制哪些 CLI 介面器。未啟用的介面器在下發時會被安全策略拒絕（ADAPTER_AUTONOMY_UNVERIFIED）。",
  autonomyEmptyNote: "未啟用任何介面器：所有程序化下發都會被拒絕，需要手動向 CLI 提交指令。",
  autonomyInstalled: "本機已偵測到",
  autonomyMissing: "未偵測到 CLI",
  autonomyAutoDispatch: "專案任務自動推進",
  autonomyAutoDispatchDescription: "CLI 回報任務完成/失敗後，自動把對應工作項推進到待評審/受阻。",
  autonomyAutoDispatchBlocked: "需先啟用至少一個介面器",
  autonomySaving: "正在儲存…",
  autonomySaved: "下發自主權已儲存。",
  autonomySaveError: "儲存失敗，請重試。",
  autonomyLoadError: "載入失敗",
  autonomyRetry: "重試",
  autonomyReadonly: "執行時間設定已被 FORGEBADGER_RUNTIME_SETTINGS_READONLY 鎖定為唯讀，請修改 .env 並重啟 Gateway。",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "設定頁",
};
export function useSettingsCopy() { const { language } = useLanguage(); return language === "en" ? en : language === "zh-TW" ? zhTW : zh; }
