import { useLanguage } from "@/hooks/use-language";
import type { FeishuNotificationType } from "@/lib/feishu-notifications-api";
import type { ChannelRouteStateKey, ChannelSetupCopy } from "@/components/copilot/channel-setup";

const zh = {
  navAriaLabel: "Copilot 设置导航",
  navGeneral: "常规",
  navExtensions: "扩展",
  navChannels: "远程渠道",
  navAutomations: "自动化",
  backToChat: "返回对话",
  channelsCardTitle: "远程渠道",
  channelsCardDescription: "配置飞书与 Telegram 远程操作：应用接入、身份确认与项目绑定。",
  channelPlatformLabel: "渠道平台",
  channelStateNotConnected: "未接入",
  channelStatePairing: "待配对",
  channelStateAuthorization: "待授权",
  channelStateRunning: "运行中",
  channelStateStopped: "已停止",
  channelStateUnknown: "待核查",
  diagnosticsFailedNotice: (count: number) => `诊断存在 ${count} 项未通过。`,
  diagnosticsExpand: "展开诊断",
  diagnosticsCollapse: "收起诊断",
  diagnosticsStatusUntested: "未验证",
  diagnosticsStatusPending: "进行中",
  diagnosticsStatusFailed: "未通过",
  copyCommand: "复制命令",
  commandCopied: "已复制",
  modifyConfig: "修改配置",
  editAllowlist: "编辑白名单",
  setAllowlist: "设置白名单",
  allowlistEmpty: "尚未设置聊天白名单。",
  identitiesEmpty: "暂无已确认身份。",
  bindingsEmpty: "尚无渠道绑定。",
  emergencyStopTitle: (name: string) => `确认紧急停止${name}？`,
  emergencyStopDescription: "紧急停止会阻止后续入站消息与操作；已经发生的操作无法撤回。",
  emergencyStopConfirm: "确认停止",
  dialogCancel: "取消",
  memoryScopeGlobal: "全局",
  memoryScopeProject: "项目",
  memoryScopeSession: "会话",
  memoryKindFact: "事实",
  memoryKindPreference: "偏好",
  memoryKindDecision: "决策",
  memoryKindProjectNote: "项目备注",
  manageModels: "管理模型",
  autonomyTitle: "任务自动推进",
  autonomyDescription: "CLI 报告任务完成/失败后，自动把对应工作项推进到待评审/受阻。程序化下发的授权在各项目的「Copilot 自治」开关上；没有按适配器的开关，所有 CLI 一律平等。",
  autonomyAutoDispatch: "项目任务自动推进",
  autonomyAutoDispatchDescription: "CLI 报告任务完成/失败后，自动把对应工作项推进到待评审/受阻。",
  autonomySaving: "正在保存…",
  autonomySaved: "自动推进设置已保存。",
  autonomySaveError: "保存失败，请重试。",
  autonomyLoadError: "加载失败",
  autonomyRetry: "重试",
  autonomyReadonly: "运行时设置已被 FORGEBADGER_RUNTIME_SETTINGS_READONLY 锁定为只读，请修改 .env 并重启 Gateway。",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "设置页",
  notifyContentHint: "通知默认包含已采集到的脱敏结果、错误和执行进度，无需额外开启；所选私聊或群聊成员均可看到这些内容。",
  notifyTitle: "飞书通知",
  notifyDescription: "选择已确认的私聊或已核验的群聊接收通知卡片。保存仅授权通知推送，不改变远程命令白名单或项目操作权限。",
  notifySwitchAria: "接收 ForgeBadger 通知",
  notifyLoading: "正在加载通知设置…",
  notifyLoadError: "通知设置加载失败。",
  notifyReload: "重新加载通知设置",
  notifyTargetLabel: "通知接收位置",
  notifyTargetPlaceholder: "选择私聊或群聊",
  notifyTargetStale: "已失效的接收位置，请重新选择",
  notifyKindGroup: "群聊",
  notifyKindPrivate: "私聊",
  notifyUnavailableSuffix: "不可用",
  notifyRefreshTargets: "刷新接收位置",
  notifyPrivateHint: "私聊来自已确认身份；刷新会核验已配置或已使用的群聊。机器人需在群内，并具备读取群列表与群成员状态的权限。",
  notifyGroupNotice: (name: string) => `所选通知将发送到群“${name}”，群成员均可查看。`,
  notifyTypesLegend: "通知类型",
  notifyWebLabel: "ForgeBadger Web 地址（可选）",
  notifyWebAria: "ForgeBadger Web 地址",
  notifyWebHint: "填写飞书所在设备能访问的地址，卡片才显示查看按钮；localhost 只指向当前设备。留空仍可接收卡片摘要。卡片不提供直接审批操作。",
  notifyBlockerFallback: "请检查通知配置。",
  notifySave: "保存通知设置",
  notifyTest: "发送测试卡片",
  notifyActionFailed: (action: string, detail: string) => `${action}失败。${detail}`,
  notifyActionRefresh: "刷新接收位置",
  notifyActionSave: "保存",
  notifyActionTest: "测试通知入队",
  notifyAuthExpired: "登录已失效，请重新登录。",
  notifyGenericError: "暂时无法完成请求，请检查 Gateway 连接后重试。",
  notifyRefreshOk: "接收位置已刷新。",
  notifyRefreshNoGroup: "未发现可用的已配置群聊，请确认机器人已加入该群。已确认私聊仍可直接选择。",
  notifySavedOn: "飞书通知已开启，只推送之后产生的通知。",
  notifySavedOff: "飞书通知已关闭，尚未发送的通知已取消。",
  notifyTestQueued: "测试卡片已入队，请查看下方投递状态和所选会话。",
  notifyDeliveriesTitle: "最近通知投递",
  notifyDeliveriesHint: "飞书已接收不代表已读；结果不确定时请先核对接收会话，系统不会自动重发。",
  notifyDeliveriesLoading: "正在加载投递记录…",
  notifyDeliveriesLoadError: "投递记录加载失败。",
  notifyDeliveriesEmpty: "暂无通知投递记录。",
  notifyTestCard: "测试卡片",
  notifyDeliveryFallback: "通知",
  notifyTypes: {
    attention: "需要处理 / 等待审批",
    failure: "任务失败 / 权限被拒绝",
    completion: "任务完成",
    lifecycle: "任务中断 / 会话结束",
    app_action: "应用操作结果",
    automation: "自动化任务结果",
  } satisfies Record<FeishuNotificationType, string>,
  notifyStatuses: {
    pending: "待发送",
    sending: "发送中",
    delivered: "飞书已接收",
    failed: "发送失败",
    unknown: "结果不确定",
    cancelled: "已取消",
  } as Record<string, string>,
  notifyBlockers: {
    IDENTITY_INVALID: "请先完成私聊身份确认。",
    ACCOUNT_CHANGED: "账号配置已变化，请重新配对身份。",
    CHANNEL_DISABLED: "请先启用飞书应用，或解除紧急停止。",
    USER_DISABLED: "当前账号已停用。",
    TARGET_INVALID: "请选择一个已确认的私聊或已核验的群聊。",
    TARGET_UNAVAILABLE: "接收位置已不可用，请刷新列表并重新选择。",
    TARGET_CHANGED: "接收位置已变化，请重新选择并保存。",
    TARGET_CONFLICT: "接收位置与旧版私聊设置冲突，请刷新页面后重新选择。",
  } as Record<string, string>,
  notifyErrors: {
    CONFIG_CONFLICT: "配置已在其他页面更新，请重新加载通知设置后再修改。",
    WEB_URL_INVALID: "Web 地址格式不正确，请使用完整的 http:// 或 https:// 地址，不包含账号密码、查询参数或 # 片段；也可以留空。",
    TYPES_REQUIRED: "请至少选择一种通知类型。",
    INPUT_INVALID: "提交的通知设置格式不正确，请检查输入。",
    SUBSCRIPTION_DISABLED: "请先开启并保存通知设置。",
    QUEUE_FULL: "待发送通知已达上限，请等待队列处理后再测试。",
    INTERNAL_ERROR: "服务端暂时无法处理通知请求，请稍后重试。",
    DIRECTORY_PERMISSION_REQUIRED: "飞书应用缺少读取群聊列表或群成员状态的权限，请在飞书开放平台补齐权限后刷新。",
    DIRECTORY_UNAVAILABLE: "暂时无法核验飞书群聊，请检查应用权限及网络后刷新；已保存的设置不会被清空。",
    DIRECTORY_INCOMPLETE: "群聊列表未能完整读取，请稍后刷新。",
  },
  // Channels: platform names
  channelNameFeishu: "飞书",
  channelNameTelegram: "Telegram",
  // Step 1: connect the app / bot
  connectionTitleFeishu: "1. 接入飞书应用",
  connectionTitleTelegram: "1. 接入 Telegram 机器人",
  connectionDescription: "本步骤连接机器人；完成第 2 步身份确认和第 3 步项目授权后，才能远程操作。",
  savedBadgeFeishu: "凭证已保存",
  savedBadgeTelegram: "Bot Token 已保存",
  notConfiguredBadgeFeishu: "尚未配置凭证",
  notConfiguredBadgeTelegram: "尚未配置 Bot Token",
  botUsername: (username: string) => `机器人 @${username}`,
  lastConnected: (time: string) => `最近连接：${time}`,
  lastError: (message: string) => `最近错误：${message}`,
  secretKeepPlaceholder: "留空保留已保存密钥",
  secretInputPlaceholder: "输入应用密钥",
  tokenKeepPlaceholder: "留空保留已保存 Token",
  saveAndEnable: "保存并启用",
  feishuReconnectHint: "更换应用凭证或重新启用后需要重新配对和绑定；保存相同配置会保留已有授权。",
  feishuPlatformHint: "飞书开放平台需开启机器人，事件订阅选择长连接并订阅 im.message.receive_v1，配置消息接收与机器人发送权限，发布应用版本并确认自己的账号在应用可用范围内。",
  feishuCardHint: "在「事件与回调 → 回调配置」中选择长连接，并添加「卡片回传交互」card.action.trigger，才能直接在飞书审批卡片中批准或拒绝操作。仅任务发起人可审批；Web Copilot 仍可处理同一审批。",
  emergencyStopNote: (telegram: boolean) => `紧急停止阻止后续入站和操作；已经发生的操作无法撤回。${telegram ? "Telegram 机器人通过长轮询接收消息，无需公网回调地址。" : ""}`,
  emergencyStopButton: (name: string) => `紧急停止${name}`,
  // Step 2: pairing & chat allowlist
  pairingTitle: "2. 确认私聊身份",
  pairingDescription: "连接成功后，还需确认哪个私聊用户可以操作项目。发送配对命令后，请回到此处确认身份。",
  createPairingCode: "生成新的配对码",
  pairingCommandHint: (name: string, time: string) => `向${name}机器人私聊发送以下命令，请勿转发。到期：${time}`,
  noPendingPairing: "没有待确认配对。新配对码会使旧码失效。",
  pairingStatusPending: "待处理",
  waitingClaim: (name: string) => `等待${name}私聊认领… 配对码仅在生成时显示，刷新页面后可重新生成。`,
  claimReviewHint: "请核对认领者，勾选后确认；系统不会自动绑定身份。",
  userIdLabelFeishu: "飞书用户 ID",
  userIdLabelTelegram: "Telegram 用户 ID",
  chatIdLabelFeishu: "私聊 ID",
  chatIdLabelTelegram: "会话 ID",
  ackLabel: (name: string) => `我确认这是自己的${name}私聊`,
  confirmIdentity: "确认身份",
  cancelPairing: "取消本次配对",
  identityStale: "已失效，需重新配对",
  revokeIdentity: "撤销身份",
  allowlistTitle: "聊天白名单（群聊与私聊）",
  allowlistHint: "群聊默认拒绝；加入白名单后，机器人在该群内被 @ 才会响应。注意：白名单非空时，不在名单内的私聊也会被拒绝，需要把自己的私聊 ID 一并加入。",
  allowlistInputLabel: "群聊与私聊 ID（逗号分隔，最多 50 个）",
  allowlistAria: "群聊白名单",
  allowlistPlaceholderFeishu: "例如：oc_群聊ID,oc_私聊ID",
  allowlistPlaceholderTelegram: "例如：-1001234567890,123456789",
  saveAllowlist: "保存白名单",
  allowlistTooMany: "最多允许 50 个聊天 ID，请减少后再保存。",
  allowlistLoadError: "白名单加载失败，请稍后重试。",
  // Step 3: binding & authorization
  bindingTitle: "3. 绑定项目与操作授权",
  bindingDescription: "私聊、群聊与话题各自使用独立会话。授权范围就是所选项目：项目的 Copilot 自治开关开启时渠道消息可直接执行，关闭后立即停止受理。",
  manageAutonomy: "管理项目 Copilot 自治开关",
  projectsLoading: "正在加载项目…",
  noAutonomyProjects: "尚无已开启 Copilot 自治的项目，请先在上方打开项目开关。",
  identityLabel: "私聊身份",
  identityPlaceholder: "选择已确认身份",
  projectLabel: "项目",
  projectPlaceholder: "选择已开启自治的项目",
  activateRemote: (name: string) => `启用${name}远程操作`,
  independentSession: (id: string) => `独立会话：${id}`,
  openConversation: "打开会话",
  revokeBinding: "撤销渠道绑定",
  // Channel status labels (raw states from the Gateway) and route states (semantic keys)
  channelStates: {
    pending: "待处理", claimed: "等待确认", confirmed: "已确认", cancelled: "已取消",
    active: "有效", revoked: "已撤销", sending: "发送中", delivered: "渠道已接收",
    failed: "发送失败", unknown: "结果不确定", connected: "已连接", connecting: "连接中",
    reconnecting: "重新连接中", unhealthy: "连接异常", stopped: "已停止", disabled: "未启用",
  } as Record<string, string>,
  routeStates: {
    authorized: "权限有效",
    pending_review: "授权状态待核查",
    identity_inactive: "身份已失效",
    config_changed: "配置已更新，需要重新绑定",
    channel_disabled: "渠道已停用",
    project_missing: "项目不存在",
    autonomy_off: "项目 Copilot 自治未开启",
    authority_revoked: "授权已失效，请撤销后重新绑定",
  } satisfies Record<ChannelRouteStateKey, string>,
  channelSetup: {
    connectionAction: "前往应用接入",
    pairingAction: "前往身份配对",
    authorizationAction: "前往项目授权",
    secretRequired: "请先在第 1 步保存机器人凭证并连接渠道。",
    configChecking: "正在核查渠道配置，请稍候。",
    configLoadFailed: "渠道配置加载失败，请重新加载后再授权。",
    channelDisabled: "渠道已停用或紧急停止，请先在第 1 步保存并连接。",
    selectIdentity: "请选择要授权的已确认私聊身份。",
    identityClaimed: "私聊已认领，请在第 2 步核对并确认身份。",
    identityPending: "请向机器人私聊发送第 2 步的配对命令，然后返回确认身份。",
    identityStale: "身份已失效，请先在第 2 步重新配对并确认身份。",
    pairFirst: "请先在第 2 步生成配对码，完成私聊认领并确认身份。",
    existingRoute: "该身份已有渠道绑定；如需重新绑定或更换项目，请先撤销下方原绑定。",
    projectsLoading: "正在加载项目，请稍候。",
    projectsError: "项目加载失败，请重新加载后再授权。",
    noAutonomyProjects: "请先打开下方项目 Copilot 自治开关，再选择项目。",
    selectProject: "请选择要授权的项目。",
  } satisfies ChannelSetupCopy,
  // Diagnostics & result deliveries
  diagnosticsTitle: (name: string) => `渠道诊断 · ${name}`,
  diagnosticsDescription: "连接、模型与回传链路的实时自检。",
  diagnosticsChecking: "正在检查渠道状态…",
  diagnosticsLoadError: "诊断加载失败，稍后自动重试。",
  diagnosticsEmpty: "暂无诊断项。",
  diagnosticsFixHint: (hint: string) => `建议：${hint}`,
  deliveriesTitle: "最近结果回传",
  deliveriesDescription: "“渠道已接收”不代表已读。“结果不确定”可能已经送达，请先核对飞书或 Telegram；系统不会自动重发。",
  deliveriesEmpty: "暂无回传记录。",
  deliveryPhaseTerminal: "任务结果",
  deliveryPhaseStatus: "状态提示",
  // Channels page status strip and actions
  channelStatusPending: "远程操作状态待核查。",
  channelStatusAuthorized: (name: string) => `${name}远程操作已授权；具体聊天仍需符合白名单，实际收发还需连接正常。`,
  channelStatusNotEnabled: (name: string, detail: string) => `${name}远程操作尚未启用。${detail}`,
  channelReadyHint: "配置已就绪，请在第 3 步确认启用。",
  actionFailedError: "操作未完成。请刷新状态后重试；身份、授权或连接状态可能已变化。",
  bindingCreated: "渠道绑定已创建；请以上方实时状态为准，状态正常后发送一条新消息。",
  channelsLoading: "正在加载渠道…",
  loadFailed: "加载失败。",
  reloadAction: "重新加载",
  activationLoadError: "渠道状态加载失败，请重新加载后再授权。",
  activationReady: "已选择身份与项目，点击按钮后授予远程操作权限。",
  // Management panel: per-project Copilot autonomy + multi-project progress
  mgmtTitle: "Copilot 项目自治",
  mgmtDescription: "打开开关即授权 Copilot 在该项目内直接执行平台动作（创建任务、创建会话、下发指令），无需逐条审批；关闭后立即停止授权，新动作会被拒绝。",
  mgmtNoProjects: "暂无项目，请先在项目页创建或导入。",
  mgmtLoadFailed: "项目加载失败",
  mgmtAutonomyOn: "已授权 Copilot 自治执行",
  mgmtAutonomyOff: "未授权",
  mgmtSaveFailed: (detail: string) => `保存失败：${detail}`,
  mgmtSwitchAria: (name: string) => `${name} Copilot 自治开关`,
  mgmtProgressTitle: "多项目进度",
  mgmtProgressDescription: "此处是账号下的项目管理视图，不会扩大会话授权范围。Copilot 的程序化下发由各项目的「Copilot 自治」开关单独授权；未开启的项目仍需人工在终端操作。",
  mgmtSupervised: "自动执行已开启",
  mgmtManualExec: "人工执行",
  mgmtNoGoal: "尚未设置目标",
  mgmtProgressSummary: (done: number, total: number, inProgress: number, blocked: number) =>
    `完成 ${done}/${total} · 进行中 ${inProgress} · 阻塞 ${blocked} · 证据 `,
  mgmtEvidenceFreshness: {
    unknown: "时间未知", stale: "已过期", fresh: "新鲜",
  } as Record<string, string>,
  mgmtOwnerNextSummary: "负责人及下一步：",
  mgmtUnassigned: "未指定",
  mgmtUnplanned: "待安排",
  mgmtOwnerLabel: "负责人",
  mgmtNextActionLabel: "下一步",
  mgmtFreshnessLabel: "证据有效小时",
  mgmtReload: "重新加载",
  mgmtSave: "保存管理信息",
  // Repair revocation kill-switch in the run options sheet
  repairRevoke: "停止本次执行的后续修复",
  repairRevoked: "已停止后续修复",
  repairRevokeError: "停止修复失败，请重试。",
};
const en: typeof zh = {
  navAriaLabel: "Copilot settings navigation",
  navGeneral: "General",
  navExtensions: "Extensions",
  navChannels: "Channels",
  navAutomations: "Automations",
  backToChat: "Back to chat",
  channelsCardTitle: "Channels",
  channelsCardDescription: "Set up Feishu and Telegram remote operation: app connection, identity confirmation, and project binding.",
  channelPlatformLabel: "Channel platform",
  channelStateNotConnected: "Not connected",
  channelStatePairing: "Pairing",
  channelStateAuthorization: "Authorization",
  channelStateRunning: "Running",
  channelStateStopped: "Stopped",
  channelStateUnknown: "Check pending",
  diagnosticsFailedNotice: (count: number) => `${count} diagnostic check${count === 1 ? "" : "s"} failing.`,
  diagnosticsExpand: "Show diagnostics",
  diagnosticsCollapse: "Hide diagnostics",
  diagnosticsStatusUntested: "Untested",
  diagnosticsStatusPending: "In progress",
  diagnosticsStatusFailed: "Failing",
  copyCommand: "Copy command",
  commandCopied: "Copied",
  modifyConfig: "Modify configuration",
  editAllowlist: "Edit allowlist",
  setAllowlist: "Set allowlist",
  allowlistEmpty: "No chat allowlist configured yet.",
  identitiesEmpty: "No confirmed identities yet.",
  bindingsEmpty: "No channel bindings yet.",
  emergencyStopTitle: (name: string) => `Emergency stop ${name}?`,
  emergencyStopDescription: "Emergency stop blocks further inbound messages and operations; operations already performed cannot be undone.",
  emergencyStopConfirm: "Stop now",
  dialogCancel: "Cancel",
  memoryScopeGlobal: "Global",
  memoryScopeProject: "Project",
  memoryScopeSession: "Session",
  memoryKindFact: "Fact",
  memoryKindPreference: "Preference",
  memoryKindDecision: "Decision",
  memoryKindProjectNote: "Project note",
  manageModels: "Manage models",
  autonomyTitle: "Auto-advance tasks",
  autonomyDescription: "When the CLI reports task completion/failure, advance the linked work item to ready-for-review/blocked automatically. Programmatic dispatch is authorized per project by its Copilot autonomy switch; there is no per-adapter switch, all CLIs are equal.",
  autonomyAutoDispatch: "Auto-advance project tasks",
  autonomyAutoDispatchDescription: "When the CLI reports task completion/failure, advance the linked work item to ready-for-review/blocked automatically.",
  autonomySaving: "Saving…",
  autonomySaved: "Auto-advance settings saved.",
  autonomySaveError: "Save failed. Please retry.",
  autonomyLoadError: "Failed to load",
  autonomyRetry: "Retry",
  autonomyReadonly: "Runtime settings are locked read-only by FORGEBADGER_RUNTIME_SETTINGS_READONLY; edit .env and restart the Gateway.",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "Settings page",
  notifyContentHint: "Notifications include captured, redacted results, errors and execution progress by default. Everyone in the selected private or group chat can see this content.",
  notifyTitle: "Feishu notifications",
  notifyDescription: "Choose a confirmed private chat or a verified group chat to receive notification cards. Saving only authorizes notification delivery; it does not change the remote command allowlist or project operation permissions.",
  notifySwitchAria: "Receive ForgeBadger notifications",
  notifyLoading: "Loading notification settings…",
  notifyLoadError: "Failed to load notification settings.",
  notifyReload: "Reload notification settings",
  notifyTargetLabel: "Notification destination",
  notifyTargetPlaceholder: "Choose a private or group chat",
  notifyTargetStale: "This destination is no longer valid; choose again",
  notifyKindGroup: "Group",
  notifyKindPrivate: "Private",
  notifyUnavailableSuffix: "unavailable",
  notifyRefreshTargets: "Refresh destinations",
  notifyPrivateHint: "Private chats come from confirmed identities; refresh verifies configured or previously used group chats. The bot must be in the group with permission to read the group list and member status.",
  notifyGroupNotice: (name: string) => `Notifications will be sent to the group “${name}”; all group members can see them.`,
  notifyTypesLegend: "Notification types",
  notifyWebLabel: "ForgeBadger web address (optional)",
  notifyWebAria: "ForgeBadger web address",
  notifyWebHint: "Enter an address reachable from the device running Feishu so the card shows a view button; localhost only points at the current device. Cards still deliver summaries when empty. Cards do not offer direct approval actions.",
  notifyBlockerFallback: "Check the notification configuration.",
  notifySave: "Save notification settings",
  notifyTest: "Send test card",
  notifyActionFailed: (action: string, detail: string) => `${action} failed. ${detail}`,
  notifyActionRefresh: "Refresh destinations",
  notifyActionSave: "Save",
  notifyActionTest: "Test notification enqueue",
  notifyAuthExpired: "Your session has expired; sign in again.",
  notifyGenericError: "The request could not be completed; check the Gateway connection and retry.",
  notifyRefreshOk: "Destinations refreshed.",
  notifyRefreshNoGroup: "No configured group chat is available. Make sure the bot has joined the group; confirmed private chats can still be selected.",
  notifySavedOn: "Feishu notifications are on; only notifications created from now on are delivered.",
  notifySavedOff: "Feishu notifications are off; unsent notifications have been cancelled.",
  notifyTestQueued: "Test card queued; check the delivery status below and the selected chat.",
  notifyDeliveriesTitle: "Recent notification deliveries",
  notifyDeliveriesHint: "Received by Feishu does not mean read; when the result is uncertain, verify the destination chat first. The system does not resend automatically.",
  notifyDeliveriesLoading: "Loading delivery records…",
  notifyDeliveriesLoadError: "Failed to load delivery records.",
  notifyDeliveriesEmpty: "No notification deliveries yet.",
  notifyTestCard: "Test card",
  notifyDeliveryFallback: "Notification",
  notifyTypes: {
    attention: "Needs action / awaiting approval",
    failure: "Task failed / permission denied",
    completion: "Task completed",
    lifecycle: "Task interrupted / session ended",
    app_action: "App action result",
    automation: "Automation task result",
  },
  notifyStatuses: {
    pending: "Pending",
    sending: "Sending",
    delivered: "Received by Feishu",
    failed: "Delivery failed",
    unknown: "Result uncertain",
    cancelled: "Cancelled",
  },
  notifyBlockers: {
    IDENTITY_INVALID: "Confirm your private-chat identity first.",
    ACCOUNT_CHANGED: "The account configuration changed; re-pair your identity.",
    CHANNEL_DISABLED: "Enable the Feishu app first, or lift the emergency stop.",
    USER_DISABLED: "This account is disabled.",
    TARGET_INVALID: "Choose a confirmed private chat or a verified group chat.",
    TARGET_UNAVAILABLE: "The destination is no longer available; refresh the list and choose again.",
    TARGET_CHANGED: "The destination has changed; choose it again and save.",
    TARGET_CONFLICT: "The destination conflicts with the legacy private-chat settings; refresh the page and choose again.",
  },
  notifyErrors: {
    CONFIG_CONFLICT: "The settings were updated on another page; reload the notification settings before editing.",
    WEB_URL_INVALID: "The web address format is invalid; use a full http:// or https:// URL without credentials, query parameters, or # fragments, or leave it empty.",
    TYPES_REQUIRED: "Select at least one notification type.",
    INPUT_INVALID: "The submitted notification settings are malformed; check your input.",
    SUBSCRIPTION_DISABLED: "Enable and save the notification settings first.",
    QUEUE_FULL: "Too many notifications are pending; wait for the queue to clear and try again.",
    INTERNAL_ERROR: "The server could not process the notification request; try again later.",
    DIRECTORY_PERMISSION_REQUIRED: "The Feishu app lacks permission to read the group chat list or member status; grant the missing permissions on the Feishu developer console and refresh.",
    DIRECTORY_UNAVAILABLE: "Group chats cannot be verified right now; check the app permissions and network, then refresh. Saved settings are not cleared.",
    DIRECTORY_INCOMPLETE: "The group list was not fully read; refresh later.",
  },
  // Channels: platform names
  channelNameFeishu: "Feishu",
  channelNameTelegram: "Telegram",
  // Step 1: connect the app / bot
  connectionTitleFeishu: "1. Connect the Feishu app",
  connectionTitleTelegram: "1. Connect the Telegram bot",
  connectionDescription: "This step connects the bot; remote operation only works after step 2 (identity confirmation) and step 3 (project authorization).",
  savedBadgeFeishu: "Credentials saved",
  savedBadgeTelegram: "Bot token saved",
  notConfiguredBadgeFeishu: "No credentials configured",
  notConfiguredBadgeTelegram: "No bot token configured",
  botUsername: (username: string) => `Bot @${username}`,
  lastConnected: (time: string) => `Last connected: ${time}`,
  lastError: (message: string) => `Last error: ${message}`,
  secretKeepPlaceholder: "Leave empty to keep the saved secret",
  secretInputPlaceholder: "Enter the app secret",
  tokenKeepPlaceholder: "Leave empty to keep the saved token",
  saveAndEnable: "Save & enable",
  feishuReconnectHint: "Changing app credentials or re-enabling requires re-pairing and re-binding; saving the same configuration keeps existing authorizations.",
  feishuPlatformHint: "In the Feishu developer console, enable the bot, choose long connection for event subscription and subscribe to im.message.receive_v1, grant message receiving and bot messaging permissions, publish an app version, and make sure your account is within the app's availability scope.",
  feishuCardHint: "Under \"Events & callbacks → callback configuration\", choose long connection and add the \"card action trigger\" (card.action.trigger) to approve or reject operations directly on Feishu approval cards. Only the task initiator may approve; the web Copilot can still handle the same approval.",
  emergencyStopNote: (telegram: boolean) => `Emergency stop blocks further inbound messages and operations; operations already performed cannot be undone.${telegram ? " Telegram bots receive messages via long polling, so no public callback URL is needed." : ""}`,
  emergencyStopButton: (name: string) => `Emergency stop ${name}`,
  // Step 2: pairing & chat allowlist
  pairingTitle: "2. Confirm private-chat identity",
  pairingDescription: "After connecting, confirm which private-chat user may operate projects. Send the pairing command, then return here to confirm the identity.",
  createPairingCode: "Generate new pairing code",
  pairingCommandHint: (name: string, time: string) => `Send the following command to the ${name} bot in a private chat; do not forward it. Expires: ${time}`,
  noPendingPairing: "No pairing awaiting confirmation. A new pairing code invalidates the previous one.",
  pairingStatusPending: "Pending",
  waitingClaim: (name: string) => `Waiting for the ${name} private chat to claim it… The pairing code is only shown when generated; regenerate it after refreshing the page.`,
  claimReviewHint: "Verify the claimant, check the box, then confirm; the system never binds an identity automatically.",
  userIdLabelFeishu: "Feishu user ID",
  userIdLabelTelegram: "Telegram user ID",
  chatIdLabelFeishu: "Private chat ID",
  chatIdLabelTelegram: "Conversation ID",
  ackLabel: (name: string) => `I confirm this is my own ${name} private chat`,
  confirmIdentity: "Confirm identity",
  cancelPairing: "Cancel this pairing",
  identityStale: "Stale; re-pair required",
  revokeIdentity: "Revoke identity",
  allowlistTitle: "Chat allowlist (groups & private chats)",
  allowlistHint: "Group chats are rejected by default; once allowlisted, the bot only responds when @-mentioned in that group. Note: when the allowlist is non-empty, private chats not in the list are also rejected, so add your own private chat ID as well.",
  allowlistInputLabel: "Group and private chat IDs (comma-separated, up to 50)",
  allowlistAria: "Chat allowlist",
  allowlistPlaceholderFeishu: "e.g. oc_groupId,oc_chatId",
  allowlistPlaceholderTelegram: "e.g. -1001234567890,123456789",
  saveAllowlist: "Save allowlist",
  allowlistTooMany: "At most 50 chat IDs are allowed; remove some before saving.",
  allowlistLoadError: "Failed to load the allowlist; retry later.",
  // Step 3: binding & authorization
  bindingTitle: "3. Bind project & operation authorization",
  bindingDescription: "Private chats, group chats, and topics each use an independent conversation. The authorization scope is the selected project: channel messages execute directly while the project's Copilot autonomy toggle is on, and stop being accepted immediately once it is off.",
  manageAutonomy: "Manage project Copilot autonomy toggles",
  projectsLoading: "Loading projects…",
  noAutonomyProjects: "No project has Copilot autonomy enabled yet; turn on a project toggle above first.",
  identityLabel: "Private-chat identity",
  identityPlaceholder: "Choose a confirmed identity",
  projectLabel: "Project",
  projectPlaceholder: "Choose a project with autonomy enabled",
  activateRemote: (name: string) => `Enable ${name} remote operation`,
  independentSession: (id: string) => `Independent conversation: ${id}`,
  openConversation: "Open conversation",
  revokeBinding: "Revoke channel binding",
  // Channel status labels (raw states from the Gateway) and route states (semantic keys)
  channelStates: {
    pending: "Pending", claimed: "Awaiting confirmation", confirmed: "Confirmed", cancelled: "Cancelled",
    active: "Active", revoked: "Revoked", sending: "Sending", delivered: "Received by channel",
    failed: "Delivery failed", unknown: "Result uncertain", connected: "Connected", connecting: "Connecting",
    reconnecting: "Reconnecting", unhealthy: "Connection unhealthy", stopped: "Stopped", disabled: "Disabled",
  } as Record<string, string>,
  routeStates: {
    authorized: "Authorized",
    pending_review: "Authorization pending review",
    identity_inactive: "Identity inactive",
    config_changed: "Configuration changed; re-bind required",
    channel_disabled: "Channel disabled",
    project_missing: "Project does not exist",
    autonomy_off: "Project Copilot autonomy is off",
    authority_revoked: "Authorization expired; revoke and re-bind",
  } satisfies Record<ChannelRouteStateKey, string>,
  channelSetup: {
    connectionAction: "Go to app connection",
    pairingAction: "Go to identity pairing",
    authorizationAction: "Go to project authorization",
    secretRequired: "Save the bot credentials and connect the channel in step 1 first.",
    configChecking: "Checking the channel configuration; please wait.",
    configLoadFailed: "Failed to load the channel configuration; reload before authorizing.",
    channelDisabled: "The channel is disabled or emergency-stopped; save and connect in step 1 first.",
    selectIdentity: "Choose a confirmed private-chat identity to authorize.",
    identityClaimed: "The private chat has been claimed; verify and confirm the identity in step 2.",
    identityPending: "Send the pairing command from step 2 to the bot in a private chat, then return to confirm the identity.",
    identityStale: "The identity is stale; re-pair and confirm it in step 2 first.",
    pairFirst: "Generate a pairing code in step 2 first, claim the private chat, and confirm the identity.",
    existingRoute: "This identity already has a channel binding; revoke the existing binding below before re-binding or switching projects.",
    projectsLoading: "Loading projects; please wait.",
    projectsError: "Failed to load projects; reload before authorizing.",
    noAutonomyProjects: "Turn on a project Copilot autonomy toggle below before choosing a project.",
    selectProject: "Choose a project to authorize.",
  } satisfies ChannelSetupCopy,
  // Diagnostics & result deliveries
  diagnosticsTitle: (name: string) => `Channel diagnostics · ${name}`,
  diagnosticsDescription: "Real-time self-checks of the connection, model, and delivery pipeline.",
  diagnosticsChecking: "Checking channel status…",
  diagnosticsLoadError: "Failed to load diagnostics; retrying automatically.",
  diagnosticsEmpty: "No diagnostic checks yet.",
  diagnosticsFixHint: (hint: string) => `Suggestion: ${hint}`,
  deliveriesTitle: "Recent result deliveries",
  deliveriesDescription: "\"Received by channel\" does not mean read. \"Result uncertain\" may already have been delivered; verify in Feishu or Telegram first. The system does not resend automatically.",
  deliveriesEmpty: "No deliveries yet.",
  deliveryPhaseTerminal: "Task result",
  deliveryPhaseStatus: "Status notice",
  // Channels page status strip and actions
  channelStatusPending: "Remote operation status needs review.",
  channelStatusAuthorized: (name: string) => `${name} remote operation is authorized; individual chats must still match the allowlist, and actual delivery also requires a healthy connection.`,
  channelStatusNotEnabled: (name: string, detail: string) => `${name} remote operation is not enabled yet. ${detail}`,
  channelReadyHint: "Configuration is ready; confirm activation in step 3.",
  actionFailedError: "The operation did not complete. Refresh and retry; the identity, authorization, or connection state may have changed.",
  bindingCreated: "Channel binding created; trust the live status above and send a new message once it looks healthy.",
  channelsLoading: "Loading channels…",
  loadFailed: "Failed to load.",
  reloadAction: "Reload",
  activationLoadError: "Failed to load channel status; reload before authorizing.",
  activationReady: "Identity and project selected; click the button to grant remote operation permission.",
  // Management panel: per-project Copilot autonomy + multi-project progress
  mgmtTitle: "Copilot project autonomy",
  mgmtDescription: "Turning the switch on authorizes Copilot to execute platform actions in that project directly (create tasks, create sessions, dispatch instructions) without per-action approval; turning it off revokes the authorization immediately and new actions are rejected.",
  mgmtNoProjects: "No projects yet. Create or import one on the Projects page first.",
  mgmtLoadFailed: "Failed to load projects",
  mgmtAutonomyOn: "Copilot autonomy authorized",
  mgmtAutonomyOff: "Not authorized",
  mgmtSaveFailed: (detail: string) => `Save failed: ${detail}`,
  mgmtSwitchAria: (name: string) => `${name} Copilot autonomy switch`,
  mgmtProgressTitle: "Multi-project progress",
  mgmtProgressDescription: "This is the project management view for the account; it does not widen session authorization. Programmatic dispatch is authorized per project by its Copilot autonomy switch; projects without it still require manual terminal operation.",
  mgmtSupervised: "Auto-execution enabled",
  mgmtManualExec: "Manual execution",
  mgmtNoGoal: "No goal set yet",
  mgmtProgressSummary: (done: number, total: number, inProgress: number, blocked: number) =>
    `Done ${done}/${total} · In progress ${inProgress} · Blocked ${blocked} · Evidence `,
  mgmtEvidenceFreshness: {
    unknown: "time unknown", stale: "stale", fresh: "fresh",
  } as Record<string, string>,
  mgmtOwnerNextSummary: "Owner & next step:",
  mgmtUnassigned: "Unassigned",
  mgmtUnplanned: "Not planned",
  mgmtOwnerLabel: "Owner",
  mgmtNextActionLabel: "Next step",
  mgmtFreshnessLabel: "Evidence validity (hours)",
  mgmtReload: "Reload",
  mgmtSave: "Save management info",
  // Repair revocation kill-switch in the run options sheet
  repairRevoke: "Stop later repairs of this run",
  repairRevoked: "Later repairs stopped",
  repairRevokeError: "Failed to stop repairs; retry.",
};
const zhTW: typeof zh = {
  ...zh,
  navAriaLabel: "Copilot 設定導覽",
  navGeneral: "一般",
  navExtensions: "擴充",
  navChannels: "遠端渠道",
  navAutomations: "自動化",
  backToChat: "返回對話",
  channelsCardTitle: "遠端渠道",
  channelsCardDescription: "設定飛書與 Telegram 遠端操作：應用接入、身份確認與專案綁定。",
  channelPlatformLabel: "渠道平台",
  channelStateNotConnected: "未接入",
  channelStatePairing: "待配對",
  channelStateAuthorization: "待授權",
  channelStateRunning: "執行中",
  channelStateStopped: "已停止",
  channelStateUnknown: "待核查",
  diagnosticsFailedNotice: (count: number) => `診斷存在 ${count} 項未通過。`,
  diagnosticsExpand: "展開診斷",
  diagnosticsCollapse: "收起診斷",
  diagnosticsStatusUntested: "未驗證",
  diagnosticsStatusPending: "進行中",
  diagnosticsStatusFailed: "未通過",
  copyCommand: "複製指令",
  commandCopied: "已複製",
  modifyConfig: "修改配置",
  editAllowlist: "編輯白名單",
  setAllowlist: "設定白名單",
  allowlistEmpty: "尚未設定聊天白名單。",
  identitiesEmpty: "暫無已確認身份。",
  bindingsEmpty: "尚無渠道綁定。",
  emergencyStopTitle: (name: string) => `確認緊急停止${name}？`,
  emergencyStopDescription: "緊急停止會阻止後續入站訊息與操作；已經發生的操作無法撤回。",
  emergencyStopConfirm: "確認停止",
  dialogCancel: "取消",
  memoryScopeGlobal: "全域",
  memoryScopeProject: "專案",
  memoryScopeSession: "會話",
  memoryKindFact: "事實",
  memoryKindPreference: "偏好",
  memoryKindDecision: "決策",
  memoryKindProjectNote: "專案備註",
  manageModels: "管理模型",
  autonomyTitle: "任務自動推進",
  autonomyDescription: "CLI 回報任務完成/失敗後，自動把對應工作項推進到待評審/受阻。程式化下發的授權在各專案的「Copilot 自治」開關上；沒有按介面器的開關，所有 CLI 一律平等。",
  autonomyAutoDispatch: "專案任務自動推進",
  autonomyAutoDispatchDescription: "CLI 回報任務完成/失敗後，自動把對應工作項推進到待評審/受阻。",
  autonomySaving: "正在儲存…",
  autonomySaved: "自動推進設定已儲存。",
  autonomySaveError: "儲存失敗，請重試。",
  autonomyLoadError: "載入失敗",
  autonomyRetry: "重試",
  autonomyReadonly: "執行時間設定已被 FORGEBADGER_RUNTIME_SETTINGS_READONLY 鎖定為唯讀，請修改 .env 並重啟 Gateway。",
  autonomySourceEnv: ".env",
  autonomySourceSettings: "設定頁",
  notifyContentHint: "通知預設包含已採集到的脫敏結果、錯誤與執行進度，無需額外開啟；所選私聊或群聊成員均可看到這些內容。",
  notifyTitle: "飛書通知",
  notifyDescription: "選擇已確認的私聊或已核驗的群聊接收通知卡片。儲存僅授權通知推送，不改變遠端指令白名單或專案操作權限。",
  notifySwitchAria: "接收 ForgeBadger 通知",
  notifyLoading: "正在載入通知設定…",
  notifyLoadError: "通知設定載入失敗。",
  notifyReload: "重新載入通知設定",
  notifyTargetLabel: "通知接收位置",
  notifyTargetPlaceholder: "選擇私聊或群聊",
  notifyTargetStale: "已失效的接收位置，請重新選擇",
  notifyKindGroup: "群聊",
  notifyKindPrivate: "私聊",
  notifyUnavailableSuffix: "不可用",
  notifyRefreshTargets: "重新整理接收位置",
  notifyPrivateHint: "私聊來自已確認身份；重新整理會核驗已配置或已使用的群聊。機器人需在群內，並具備讀取群列表與群成員狀態的權限。",
  notifyGroupNotice: (name: string) => `所選通知將傳送到群「${name}」，群成員均可查看。`,
  notifyTypesLegend: "通知類型",
  notifyWebLabel: "ForgeBadger Web 地址（可選）",
  notifyWebAria: "ForgeBadger Web 地址",
  notifyWebHint: "填寫飛書所在裝置能存取的地址，卡片才顯示查看按鈕；localhost 只指向目前裝置。留空仍可接收卡片摘要。卡片不提供直接審批操作。",
  notifyBlockerFallback: "請檢查通知配置。",
  notifySave: "儲存通知設定",
  notifyTest: "傳送測試卡片",
  notifyActionFailed: (action: string, detail: string) => `${action}失敗。${detail}`,
  notifyActionRefresh: "重新整理接收位置",
  notifyActionSave: "儲存",
  notifyActionTest: "測試通知入隊",
  notifyAuthExpired: "登入已失效，請重新登入。",
  notifyGenericError: "暫時無法完成請求，請檢查 Gateway 連線後重試。",
  notifyRefreshOk: "接收位置已重新整理。",
  notifyRefreshNoGroup: "未發現可用的已配置群聊，請確認機器人已加入該群。已確認私聊仍可直接選擇。",
  notifySavedOn: "飛書通知已開啟，只推送之後產生的通知。",
  notifySavedOff: "飛書通知已關閉，尚未傳送的通知已取消。",
  notifyTestQueued: "測試卡片已入隊，請查看下方投遞狀態與所選會話。",
  notifyDeliveriesTitle: "最近通知投遞",
  notifyDeliveriesHint: "飛書已接收不代表已讀；結果不確定時請先核對接收會話，系統不會自動重發。",
  notifyDeliveriesLoading: "正在載入投遞記錄…",
  notifyDeliveriesLoadError: "投遞記錄載入失敗。",
  notifyDeliveriesEmpty: "暫無通知投遞記錄。",
  notifyTestCard: "測試卡片",
  notifyDeliveryFallback: "通知",
  notifyTypes: {
    attention: "需要處理 / 等待審批",
    failure: "任務失敗 / 權限被拒絕",
    completion: "任務完成",
    lifecycle: "任務中斷 / 會話結束",
    app_action: "應用操作結果",
    automation: "自動化任務結果",
  },
  notifyStatuses: {
    pending: "待發送",
    sending: "發送中",
    delivered: "飛書已接收",
    failed: "發送失敗",
    unknown: "結果不確定",
    cancelled: "已取消",
  },
  notifyBlockers: {
    IDENTITY_INVALID: "請先完成私聊身份確認。",
    ACCOUNT_CHANGED: "帳號配置已變化，請重新配對身份。",
    CHANNEL_DISABLED: "請先啟用飛書應用，或解除緊急停止。",
    USER_DISABLED: "目前帳號已停用。",
    TARGET_INVALID: "請選擇一個已確認的私聊或已核驗的群聊。",
    TARGET_UNAVAILABLE: "接收位置已不可用，請重新整理列表並重新選擇。",
    TARGET_CHANGED: "接收位置已變化，請重新選擇並儲存。",
    TARGET_CONFLICT: "接收位置與舊版私聊設定衝突，請重新整理頁面後重新選擇。",
  },
  notifyErrors: {
    CONFIG_CONFLICT: "配置已在其他頁面更新，請重新載入通知設定後再修改。",
    WEB_URL_INVALID: "Web 地址格式不正確，請使用完整的 http:// 或 https:// 地址，不包含帳號密碼、查詢參數或 # 片段；也可以留空。",
    TYPES_REQUIRED: "請至少選擇一種通知類型。",
    INPUT_INVALID: "提交的通知設定格式不正確，請檢查輸入。",
    SUBSCRIPTION_DISABLED: "請先開啟並儲存通知設定。",
    QUEUE_FULL: "待發送通知已達上限，請等待佇列處理後再測試。",
    INTERNAL_ERROR: "服務端暫時無法處理通知請求，請稍後重試。",
    DIRECTORY_PERMISSION_REQUIRED: "飛書應用缺少讀取群聊列表或群成員狀態的權限，請在飛書開放平台補齊權限後重新整理。",
    DIRECTORY_UNAVAILABLE: "暫時無法核驗飛書群聊，請檢查應用權限及網路後重新整理；已儲存的設定不會被清空。",
    DIRECTORY_INCOMPLETE: "群聊列表未能完整讀取，請稍後重新整理。",
  },
  // Channels: platform names
  channelNameFeishu: "飛書",
  channelNameTelegram: "Telegram",
  // Step 1: connect the app / bot
  connectionTitleFeishu: "1. 接入飛書應用",
  connectionTitleTelegram: "1. 接入 Telegram 機器人",
  connectionDescription: "本步驟連接機器人；完成第 2 步身份確認和第 3 步專案授權後，才能遠端操作。",
  savedBadgeFeishu: "憑證已儲存",
  savedBadgeTelegram: "Bot Token 已儲存",
  notConfiguredBadgeFeishu: "尚未配置憑證",
  notConfiguredBadgeTelegram: "尚未配置 Bot Token",
  botUsername: (username: string) => `機器人 @${username}`,
  lastConnected: (time: string) => `最近連接：${time}`,
  lastError: (message: string) => `最近錯誤：${message}`,
  secretKeepPlaceholder: "留空保留已儲存金鑰",
  secretInputPlaceholder: "輸入應用金鑰",
  tokenKeepPlaceholder: "留空保留已儲存 Token",
  saveAndEnable: "儲存並啟用",
  feishuReconnectHint: "更換應用憑證或重新啟用後需要重新配對和綁定；儲存相同配置會保留已有授權。",
  feishuPlatformHint: "飛書開放平台需開啟機器人，事件訂閱選擇長連接並訂閱 im.message.receive_v1，配置訊息接收與機器人發送權限，發布應用版本並確認自己的帳號在應用可用範圍內。",
  feishuCardHint: "在「事件與回調 → 回調配置」中選擇長連接，並新增「卡片回傳互動」card.action.trigger，才能直接在飛書審批卡片中批准或拒絕操作。僅任務發起人可審批；Web Copilot 仍可處理同一審批。",
  emergencyStopNote: (telegram: boolean) => `緊急停止會阻止後續入站訊息與操作；已經發生的操作無法撤回。${telegram ? "Telegram 機器人透過長輪詢接收訊息，無需公網回調地址。" : ""}`,
  emergencyStopButton: (name: string) => `緊急停止${name}`,
  // Step 2: pairing & chat allowlist
  pairingTitle: "2. 確認私聊身份",
  pairingDescription: "連接成功後，還需確認哪個私聊使用者可以操作專案。發送配對命令後，請回到此處確認身份。",
  createPairingCode: "產生新的配對碼",
  pairingCommandHint: (name: string, time: string) => `向${name}機器人私聊發送以下命令，請勿轉發。到期：${time}`,
  noPendingPairing: "沒有待確認配對。新配對碼會使舊碼失效。",
  pairingStatusPending: "待處理",
  waitingClaim: (name: string) => `等待${name}私聊認領… 配對碼僅在產生時顯示，重新整理頁面後可重新產生。`,
  claimReviewHint: "請核對認領者，勾選後確認；系統不會自動綁定身份。",
  userIdLabelFeishu: "飛書使用者 ID",
  userIdLabelTelegram: "Telegram 使用者 ID",
  chatIdLabelFeishu: "私聊 ID",
  chatIdLabelTelegram: "會話 ID",
  ackLabel: (name: string) => `我確認這是自己的${name}私聊`,
  confirmIdentity: "確認身份",
  cancelPairing: "取消本次配對",
  identityStale: "已失效，需重新配對",
  revokeIdentity: "撤銷身份",
  allowlistTitle: "聊天白名單（群聊與私聊）",
  allowlistHint: "群聊預設拒絕；加入白名單後，機器人在該群內被 @ 才會回應。注意：白名單非空時，不在名單內的私聊也會被拒絕，需要把自己的私聊 ID 一併加入。",
  allowlistInputLabel: "群聊與私聊 ID（逗號分隔，最多 50 個）",
  allowlistAria: "聊天白名單",
  allowlistPlaceholderFeishu: "例如：oc_群聊ID,oc_私聊ID",
  allowlistPlaceholderTelegram: "例如：-1001234567890,123456789",
  saveAllowlist: "儲存白名單",
  allowlistTooMany: "最多允許 50 個聊天 ID，請減少後再儲存。",
  allowlistLoadError: "白名單載入失敗，請稍後重試。",
  // Step 3: binding & authorization
  bindingTitle: "3. 綁定專案與操作授權",
  bindingDescription: "私聊、群聊與話題各自使用獨立會話。授權範圍就是所選專案：專案的 Copilot 自治開關開啟時渠道訊息可直接執行，關閉後立即停止受理。",
  manageAutonomy: "管理專案 Copilot 自治開關",
  projectsLoading: "正在載入專案…",
  noAutonomyProjects: "尚無已開啟 Copilot 自治的專案，請先在上方打開專案開關。",
  identityLabel: "私聊身份",
  identityPlaceholder: "選擇已確認身份",
  projectLabel: "專案",
  projectPlaceholder: "選擇已開啟自治的專案",
  activateRemote: (name: string) => `啟用${name}遠端操作`,
  independentSession: (id: string) => `獨立會話：${id}`,
  openConversation: "打開會話",
  revokeBinding: "撤銷渠道綁定",
  // Channel status labels (raw states from the Gateway) and route states (semantic keys)
  channelStates: {
    pending: "待處理", claimed: "等待確認", confirmed: "已確認", cancelled: "已取消",
    active: "有效", revoked: "已撤銷", sending: "發送中", delivered: "渠道已接收",
    failed: "發送失敗", unknown: "結果不確定", connected: "已連接", connecting: "連接中",
    reconnecting: "重新連接中", unhealthy: "連接異常", stopped: "已停止", disabled: "未啟用",
  } as Record<string, string>,
  routeStates: {
    authorized: "權限有效",
    pending_review: "授權狀態待核查",
    identity_inactive: "身份已失效",
    config_changed: "配置已更新，需要重新綁定",
    channel_disabled: "渠道已停用",
    project_missing: "專案不存在",
    autonomy_off: "專案 Copilot 自治未開啟",
    authority_revoked: "授權已失效，請撤銷後重新綁定",
  } satisfies Record<ChannelRouteStateKey, string>,
  channelSetup: {
    connectionAction: "前往應用接入",
    pairingAction: "前往身份配對",
    authorizationAction: "前往專案授權",
    secretRequired: "請先在第 1 步儲存機器人憑證並連接渠道。",
    configChecking: "正在核查渠道配置，請稍候。",
    configLoadFailed: "渠道配置載入失敗，請重新載入後再授權。",
    channelDisabled: "渠道已停用或緊急停止，請先在第 1 步儲存並連接。",
    selectIdentity: "請選擇要授權的已確認私聊身份。",
    identityClaimed: "私聊已認領，請在第 2 步核對並確認身份。",
    identityPending: "請向機器人私聊發送第 2 步的配對命令，然後返回確認身份。",
    identityStale: "身份已失效，請先在第 2 步重新配對並確認身份。",
    pairFirst: "請先在第 2 步產生配對碼，完成私聊認領並確認身份。",
    existingRoute: "該身份已有渠道綁定；如需重新綁定或更換專案，請先撤銷下方原綁定。",
    projectsLoading: "正在載入專案，請稍候。",
    projectsError: "專案載入失敗，請重新載入後再授權。",
    noAutonomyProjects: "請先打開下方專案 Copilot 自治開關，再選擇專案。",
    selectProject: "請選擇要授權的專案。",
  } satisfies ChannelSetupCopy,
  // Diagnostics & result deliveries
  diagnosticsTitle: (name: string) => `渠道診斷 · ${name}`,
  diagnosticsDescription: "連接、模型與回傳鏈路的即時自檢。",
  diagnosticsChecking: "正在檢查渠道狀態…",
  diagnosticsLoadError: "診斷載入失敗，稍後自動重試。",
  diagnosticsEmpty: "暫無診斷項。",
  diagnosticsFixHint: (hint: string) => `建議：${hint}`,
  deliveriesTitle: "最近結果回傳",
  deliveriesDescription: "「渠道已接收」不代表已讀。「結果不確定」可能已經送達，請先核對飛書或 Telegram；系統不會自動重發。",
  deliveriesEmpty: "暫無回傳記錄。",
  deliveryPhaseTerminal: "任務結果",
  deliveryPhaseStatus: "狀態提示",
  // Channels page status strip and actions
  channelStatusPending: "遠端操作狀態待核查。",
  channelStatusAuthorized: (name: string) => `${name}遠端操作已授權；具體聊天仍需符合白名單，實際收發還需連接正常。`,
  channelStatusNotEnabled: (name: string, detail: string) => `${name}遠端操作尚未啟用。${detail}`,
  channelReadyHint: "配置已就緒，請在第 3 步確認啟用。",
  actionFailedError: "操作未完成。請重新整理狀態後重試；身份、授權或連接狀態可能已變化。",
  bindingCreated: "渠道綁定已建立；請以上方即時狀態為準，狀態正常後發送一條新訊息。",
  channelsLoading: "正在載入渠道…",
  loadFailed: "載入失敗。",
  reloadAction: "重新載入",
  activationLoadError: "渠道狀態載入失敗，請重新載入後再授權。",
  activationReady: "已選擇身份與專案，點擊按鈕後授予遠端操作權限。",
  // Management panel: per-project Copilot autonomy + multi-project progress
  mgmtTitle: "Copilot 專案自治",
  mgmtDescription: "打開開關即授權 Copilot 在該專案內直接執行平台動作（建立任務、建立會話、下發指令），無需逐條審批；關閉後立即停止授權，新動作會被拒絕。",
  mgmtNoProjects: "暫無專案，請先在專案頁建立或匯入。",
  mgmtLoadFailed: "專案載入失敗",
  mgmtAutonomyOn: "已授權 Copilot 自治執行",
  mgmtAutonomyOff: "未授權",
  mgmtSaveFailed: (detail: string) => `儲存失敗：${detail}`,
  mgmtSwitchAria: (name: string) => `${name} Copilot 自治開關`,
  mgmtProgressTitle: "多專案進度",
  mgmtProgressDescription: "此處是帳號下的專案管理檢視，不會擴大會話授權範圍。Copilot 的程式化下發由各專案的「Copilot 自治」開關單獨授權；未開啟的專案仍需人工在終端操作。",
  mgmtSupervised: "自動執行已開啟",
  mgmtManualExec: "人工執行",
  mgmtNoGoal: "尚未設定目標",
  mgmtProgressSummary: (done: number, total: number, inProgress: number, blocked: number) =>
    `完成 ${done}/${total} · 進行中 ${inProgress} · 阻塞 ${blocked} · 證據 `,
  mgmtEvidenceFreshness: {
    unknown: "時間未知", stale: "已過期", fresh: "新鮮",
  } as Record<string, string>,
  mgmtOwnerNextSummary: "負責人及下一步：",
  mgmtUnassigned: "未指定",
  mgmtUnplanned: "待安排",
  mgmtOwnerLabel: "負責人",
  mgmtNextActionLabel: "下一步",
  mgmtFreshnessLabel: "證據有效小時",
  mgmtReload: "重新載入",
  mgmtSave: "儲存管理資訊",
  // Repair revocation kill-switch in the run options sheet
  repairRevoke: "停止本次執行的後續修復",
  repairRevoked: "已停止後續修復",
  repairRevokeError: "停止修復失敗，請重試。",
};
export function useSettingsCopy() { const { language } = useLanguage(); return language === "en" ? en : language === "zh-TW" ? zhTW : zh; }
