import assert from 'node:assert/strict';
import { it } from 'node:test';
import { mkdtempSync,mkdirSync,readFileSync,writeFileSync,copyFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { UserRepository } from '../src/db/repositories/user-repository.js';
import { CopilotConversationLog } from '../src/services/agent/conversation-log.js';
import { CopilotRunLedger } from '../src/services/agent/run-ledger.js';
it('upgrades populated 0085 without changing legacy evidence; backups and keyed admission survive reopen',async()=>{
  const dir=mkdtempSync(path.join(tmpdir(),'copilot-request-migration-'));
  const root=new URL('../src/db/migrations/',import.meta.url).pathname;
  const legacy=path.join(dir,'legacy');mkdirSync(path.join(legacy,'meta'),{recursive:true});
  const journal=JSON.parse(readFileSync(path.join(root,'meta/_journal.json'),'utf8')) as {entries:{tag:string}[]};
  journal.entries=journal.entries.filter(e=>Number(e.tag.slice(0,4))<=85);
  writeFileSync(path.join(legacy,'meta/_journal.json'),JSON.stringify(journal));
  for(const e of journal.entries)copyFileSync(path.join(root,e.tag+'.sql'),path.join(legacy,e.tag+'.sql'));
  const filename=path.join(dir,'fixture.db');let db=new Database(filename);
  try{
    migrate(drizzle(db),{migrationsFolder:legacy});
    const user=new UserRepository(db).create('migration-request@test.dev','hash');
    const log=new CopilotConversationLog(db,user.id);const c=log.createConversation();
    const oldRun=log.createRun(c.id,{});log.updateRun(oldRun.id,{status:'completed'});
    const ledger=new CopilotRunLedger(db,user.id);
    const step=ledger.addStep(oldRun.id,{kind:'tool',toolName:'list_projects',toolCallId:'legacy-call',inputJson:'{}'});
    ledger.completeStep(step.id,'{"ok":true,"output":{"projects":[]}}');
    ledger.append(oldRun.id,{role:'tool',kind:'tool_result',toolName:'list_projects',toolCallId:'legacy-call',content:'{"ok":true,"output":{"projects":[]}}'},step.id);
    const oldMessages=db.prepare('SELECT * FROM copilot_messages').all();
    const oldSteps=db.prepare('SELECT * FROM copilot_run_steps').all();
    const oldRunRow=db.prepare('SELECT * FROM copilot_runs WHERE id=?').get(oldRun.id) as Record<string,unknown>;
    await db.backup(path.join(dir,'before.db'));
    migrate(drizzle(db),{migrationsFolder:root});
    const upgraded=db.prepare('SELECT * FROM copilot_runs WHERE id=?').get(oldRun.id) as Record<string,unknown>;
    assert.deepEqual(upgraded,{...oldRunRow,client_request_id:null,request_digest:null});
    assert.deepEqual(db.prepare('SELECT * FROM copilot_messages').all(),oldMessages);
    assert.deepEqual(db.prepare('SELECT * FROM copilot_run_steps').all(),oldSteps);
    migrate(drizzle(db),{migrationsFolder:root});
    const input={userId:user.id,conversationId:c.id,userText:'one logical request',clientRequestId:'persisted-key'};
    const keyed=ledger.admit(input,5);ledger.cancel(keyed);
    await db.backup(path.join(dir,'after.db'));
    db.close();db=new Database(filename);
    assert.equal(new CopilotRunLedger(db,user.id).admit(input,5),keyed);
    assert.throws(()=>new CopilotRunLedger(db,user.id).admit({...input,userText:'changed'},5),/payload|request|conflict/i);
    assert.deepEqual(db.pragma('foreign_key_check'),[]);assert.equal(db.pragma('integrity_check',{simple:true}),'ok');
    db.close();copyFileSync(path.join(dir,'before.db'),filename);db=new Database(filename);
    assert.equal((db.prepare('PRAGMA table_info(copilot_runs)').all() as {name:string}[]).some(c=>c.name==='client_request_id'),false);
    assert.deepEqual(db.prepare('SELECT * FROM copilot_run_steps').all(),oldSteps);
    assert.deepEqual(db.prepare('SELECT * FROM copilot_messages').all(),oldMessages);
    migrate(drizzle(db),{migrationsFolder:root});assert.equal(new CopilotConversationLog(db,user.id).getRun(oldRun.id)?.status,'completed');
    db.close();copyFileSync(path.join(dir,'after.db'),filename);db=new Database(filename);
    assert.equal(new CopilotRunLedger(db,user.id).admit(input,5),keyed);
    assert.equal((db.prepare('SELECT count(*) n FROM copilot_runs').get() as {n:number}).n,2);
    assert.deepEqual(db.pragma('foreign_key_check'),[]);
  }finally{if(db.open)db.close();rmSync(dir,{recursive:true,force:true});}
});
