import {Router,type Request,type Response} from 'express';
import {z} from 'zod';
import {authenticate,type AuthenticatedRequest} from '../auth/middleware.js';
import {TeamService} from '../services/teams/service.js';
import {CollaborationError} from '../services/collaboration/types.js';
import type {DeliveryService} from '../services/collaboration/delivery-service.js';
const id=z.string().uuid(),revision=z.number().int().min(1),empty=z.object({}).strict();
const token=z.string().regex(/^[a-zA-Z0-9_-]{43}$/),actor=(req:Request)=>(req as unknown as AuthenticatedRequest).userId;
export function createTeamRoutes(delivery:DeliveryService):Router {const router=Router(),s=new TeamService(delivery);router.use(authenticate);
 const team=(req:Request)=>id.parse(req.params.teamId),member=(req:Request)=>id.parse(req.params.userId),plan=(req:Request)=>id.parse(req.params.planId);
 const handle=(fn:(req:Request)=>unknown|Promise<unknown>,status=200)=>(req:Request,res:Response)=>{void Promise.resolve().then(()=>fn(req)).then(data=>res.status(status).json({code:0,data,message:''})).catch(error=>{const known=error instanceof CollaborationError,invalid=error instanceof z.ZodError;const raw=error instanceof Error?error.message:'';const code=known?error.code:invalid?'INVALID_INPUT':raw.includes('DELIVERY_INTEGRATION_IN_PROGRESS')?'DELIVERY_INTEGRATION_IN_PROGRESS':'TEAM_OPERATION_FAILED';res.status(known?error.status:invalid?400:409).json({code:1,message:code,details:{code}});});};
 router.get('/',handle(req=>({teams:s.repo(actor(req)).list()})));
 router.post('/',handle(req=>({team:s.repo(actor(req)).create(z.object({name:z.string().trim().min(1).max(100)}).strict().parse(req.body).name)}),201));
 router.post('/invitations/accept',handle(req=>s.invites.accept(actor(req),z.object({token}).strict().parse(req.body).token)));
 router.get('/:teamId',handle(req=>s.detail(actor(req),team(req))));
 router.patch('/:teamId',handle(req=>{const b=z.object({name:z.string().trim().min(1).max(100),expectedRevision:revision}).strict().parse(req.body);return {team:s.repo(actor(req)).rename(team(req),b.name,b.expectedRevision)};}));
 router.post('/:teamId/transfer-owner',handle(req=>{const b=z.object({newOwnerId:id,expectedRevision:revision}).strict().parse(req.body);return {team:s.repo(actor(req)).transfer(team(req),b.newOwnerId,b.expectedRevision)};}));
 router.post('/:teamId/close',handle(req=>({team:s.repo(actor(req)).close(team(req),z.object({expectedRevision:revision}).strict().parse(req.body).expectedRevision)})));
 router.patch('/:teamId/members/:userId',handle(req=>{const b=z.object({role:z.enum(['admin','member']),expectedRevision:revision}).strict().parse(req.body);return s.repo(actor(req)).changeRole(team(req),member(req),b.role,b.expectedRevision);}));
 router.get('/:teamId/enrollment-candidates',handle(req=>({projects:s.candidates(actor(req),team(req))})));
 router.post('/:teamId/projects',handle(async req=>{const b=z.object({projectId:id,expectedProjectRevision:z.number().int().min(0),expectedTeamRevision:revision}).strict().parse(req.body);return {project:await s.enroll(actor(req),team(req),b.projectId,b.expectedProjectRevision,b.expectedTeamRevision)};},201));
 router.post('/:teamId/projects/:projectId/transfer-owner',handle(req=>{const b=z.object({newOwnerId:id,expectedRevision:revision}).strict().parse(req.body);return {project:s.transferProject(actor(req),team(req),id.parse(req.params.projectId),b.newOwnerId,b.expectedRevision)};}));
 router.get('/:teamId/invitations',handle(req=>({invitations:s.invites.list(actor(req),team(req))})));
 router.post('/:teamId/invitations',handle(req=>{const b=z.object({email:z.string().email().max(254),role:z.enum(['admin','member']),expiresInHours:z.number().int().min(1).max(168).optional()}).strict().parse(req.body);return s.invites.issue(actor(req),team(req),b.email,b.role,b.expiresInHours);},201));
 router.delete('/:teamId/invitations/:inviteId',handle(req=>s.invites.revoke(actor(req),team(req),id.parse(req.params.inviteId))));
 router.get('/:teamId/members/:userId/offboarding',handle(req=>({impact:s.impact(actor(req),team(req),member(req))})));
 router.get('/:teamId/offboarding-plans',handle(req=>s.plans(actor(req),team(req))));
 router.post('/:teamId/offboarding-plans',handle(req=>{const b=z.object({memberId:id,expectedMemberRevision:revision,expectedImpactDigest:z.string().regex(/^[a-f0-9]{64}$/),handoffs:z.array(z.object({projectId:id,newOwnerId:id.optional(),assigneeId:id.nullable(),reviewerId:id.nullable()}).strict()).max(1000)}).strict().parse(req.body);return s.plan(actor(req),team(req),b.memberId,b.expectedMemberRevision,b.handoffs,b.expectedImpactDigest);},201));
 router.get('/:teamId/offboarding-plans/:planId',handle(req=>s.planStatus(actor(req),team(req),plan(req))));
 router.post('/:teamId/offboarding-plans/:planId/commit',handle(req=>s.commit(actor(req),team(req),plan(req),z.object({confirmationToken:token}).strict().parse(req.body).confirmationToken)));
 router.patch('/:teamId/offboarding-plans/:planId',handle(req=>{const b=z.object({expectedPlanRevision:revision,expectedImpactDigest:z.string().regex(/^[a-f0-9]{64}$/),handoffs:z.array(z.object({projectId:id,newOwnerId:id.optional(),assigneeId:id.nullable(),reviewerId:id.nullable()}).strict()).max(1000)}).strict().parse(req.body);return s.repair(actor(req),team(req),plan(req),b.expectedPlanRevision,b.expectedImpactDigest,b.handoffs);}));
 router.post('/:teamId/offboarding-plans/:planId/resume',handle(req=>{empty.parse(req.body);return s.resume(actor(req),team(req),plan(req));}));
 return router;
}
